<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css')
    ->appendStylesheet('/assets/bootstrap-datepicker/css/datepicker.css')
;

$this->inlineScript()
    ->appendFile('/assets/fileajax/jquery.fileajax.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/assets/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile('/js/forms/project/commissioning.js');

$url = '/client-' . $project->getClient()->getClientId() . '/project-' . $project->getProjectId() . '/commissioninguploaddrawing/';

$this->inlineScript()->captureStart();
echo <<<JS
    $(function(){
        $('#FormUploadDrawing').fileAjax(
            {
                url: "{$url}"
            },
            function(data){
                try{
                    var success = false;
                    if(data.length) {
                        obj = $.parseJSON(data);
                        if (obj.error) {
                            errtxt = '';

                            var msg = "The drawing could not be attached to drawing." +
                                    (!!obj.info ? "<br><br>" + obj.info : "" ) +
                                    "<br><br>Please contact support if this problem persists.";
                            growl('Error!', msg, {});
                        } else { // no error
                            growl('Image Uploaded Successfully!', 'The selected image has been uploaded and applied to the drawing successfully', {});
                            var drawingRow = $('#tbl_status tr[data-drawing-id="' + obj.drawing.DrawingID + '"]');
                            if (!!drawingRow) {
                                drawingRow.find('td:nth-child(2)').text(obj.drawing.Width + 'px');
                                drawingRow.find('td:nth-child(3)').text(obj.drawing.Height + 'px');
                                if (!!obj.drawing.Activated) {
                                    drawingRow.find('td:nth-child(4)').text('Yes');
                                    drawingRow.find('.activate-drawing-image').hide();
                                    drawingRow.find('.deactivate-drawing-image').show();
                                } else {
                                    drawingRow.find('td:nth-child(4)').text('No');
                                    drawingRow.find('.activate-drawing-image').show();
                                    drawingRow.find('.deactivate-drawing-image').hide();
                                }
                            }
                            $('#modalUploadDrawing').modal('hide');
                        }
                    }
                } catch (e) {
                    console.log(data);
                    growl('Oops - something went wrong!', "There was an issue saving the image to the drawing.<br><br>Please contact support if this problem persists.", {});
                } finally {
                    $('#uploadDrawingLoader').fadeOut(function(){});
                }
            },
            function(){
                $('#uploadDrawingLoader').fadeIn(function(){});
                if (!$('input[name=file]').val().length) {
                    $('#uploadDrawingLoader').fadeOut(function(){});
                    growl('Error!', 'You must an image in order to proceed.', {});
                    return false;
                }

                return true;
            }
        );


    });

JS;
$this->inlineScript()->captureEnd();

?>
<div id="modalUploadDrawing" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Upload Drawing Image&nbsp;</h3>
    </div>
    <div class="modal-body">
        <form id="FormUploadDrawing" name="FormUploadDrawing" enctype="multipart/form-data" method="post" accept-charset="UTF-8" action="<?php
            echo $url;
        ?>" class="form-nomargin">
            <input name="DrawingID" value="" type="hidden" />
            <div id="uploadDrawingLoader" class="loader"></div>
            <p>
                Please select the image that you wish to attach to the selected drawing.<br />
                <span class="text-info"><strong>Important:</strong> images should be in jpg or png format</span><br /><br />
                <span id="lbl-file-info" class="label label-important">No file selected</span>&nbsp;&nbsp;
                <a id="btn-select-file" class="btn btn-small" href="javascript:">select file</a>
                <input type="file" name="file" accept="image/jpeg,image/png" style="visibility: hidden; width: 1px;" /><br /><br />
                Please note: this will upload an image for the drawing which will replace any pre-existing images.
            </p>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-upload-drawing" aria-hidden="true"><i class="icon-ok"></i> Confirm</button>
    </div>
</div>
<div class="relative">
    <div id="commissioningLoader" class="loader"></div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget green">
                <div class="widget-title">
                    <h4><i class="icon-list"></i> Commissioning Progress</h4>
                    <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                    <a href="javascript:;" class="icon-remove"></a>
                    </span>
                </div>
                <div class="widget-body relative">
                    <div class="space10"></div>
                    <div class="navbar navbar-static" id="navbar-example">
                        <div class="navbar-inner">
                            <div style="width: auto;" class="container">
                                <a href="#" class="brand">Options</a>
                                <ul role="navigation" class="nav">
                                    <li class="dropdown">
                                        <a data-toggle="dropdown" class="dropdown-toggle" role="button" id="drop2" href="#">Downloads <b class="caret"></b></a>
                                        <ul aria-labelledby="drop2" role="menu" class="dropdown-menu">
                                            <?php
                                            if ($project->getLipProject() && $project->getInstalled()) {
                                            ?>
                                                <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/commissioningcertificate/" tabindex="-1" role="menuitem" target="_tab">Commissioning Certificate (View)</a></li>
                                                <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/commissioningcertificate/?download=true" tabindex="-1" role="menuitem">Commissioning Certificate (Download)</a></li>
                                            <?php
                                            } else {
                                            ?>
                                            <li role="presentation"><a
                                                    href="javascript:"
                                                    tabindex="-1" role="menuitem">None Available</a></li>
                                            <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form name="frmSaveStatus" id="frmUpdateLinkedBranch" class="form-nomargin" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/commissioningupdatelinkedbranch/">
                        <table class="table table-bordered table-striped" id="tbl_linked_branch">
                            <thead>
                            <tr>
                                <th colspan="2">Linked Branch Configuration</th>
                            </tr>
                            <tr>
                                <td colspan="2">The project needs to be linked to a branch that has been uploaded from the telemetry system.  To link to a branch select the branch from the drop-down list
                                    and click on the &quot;update linked branch&quot; button<br /><span class="text-error">Warning:</span> only 1 project can be linked to a specific branch - please ensure that the selected branch is correct before updating</td>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th style="width: 250px">Linked Branch</th>
                                <td ><?php echo $project->getLipProject() ? $project->getLipProject()->assemble() : 'none'; ?></td>
                            </tr>
                            <tr>
                                <th style="vertical-align: middle;">Assigned Branch</th>
                                <td ><select style="margin: 0" name="ProjectID" id="ProjectID"><option>Please Select</option><option value="0">Un-Link Branch</option><?php
                                        foreach ($unassigned as $lipProject) {
                                            echo '<option value="' . $lipProject->getProjectID() . '">' . $lipProject->assemble() . '</option>';
                                        }
                                        ?></select>
                                    <button class="btn btn-primary " id="btn-synchronize" action="/branch/synchronize/?projects=true&drawings=true&flash=true"><i class="icon-refresh"></i></button>
                                </td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="2"><button class="btn btn-primary" id="btn-update-linked-branch"><i class="icon-warning-sign"></i> Update Linked Branch</button></td>
                            </tr>
                            </tfoot>
                        </table>
                    </form>
                    <div class="space20"></div>
                    <?php echo $this->form()->openTag($commissioningSetupForm); ?>
                        <table class="table table-bordered table-striped" id="tbl_status">
                            <thead>
                            <tr>
                                <th colspan="2">Project Setup</th>
                            </tr>
                            <tr>
                                <td colspan="2">Below are the branch specific items that need to be setup for the project.</td>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td style="width: 250px">Installation Date</td>
                                <td>
                                    <div class="controls">
                                        <div class="input-append no-margin-bot" id="dpYears" data-date="12-02-2012" data-date-format="dd-mm-yyyy" >
                                            <?php echo $this->formElement($commissioningSetupForm->get('installed'));  ?>
                                            <span class="add-on" id="startDtIcon"><i class="icon-calendar"></i></span>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Commissioned Date</td>
                                <td>
                                    <div class="controls">
                                        <div class="input-append no-margin-bot" id="dpYears" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
                                            <?php echo $this->formElement($commissioningSetupForm->get('commissioned'));  ?>
                                            <span class="add-on" id="startDtIcon"><i class="icon-calendar"></i></span>
                                        </div>
                                    </div>

                                </td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="2"><button class="btn btn-primary" id="btn-save-config"><i class="icon-ok icon-white"></i> Save Project Config</button></td>
                            </tr>
                            </tfoot>
                        </table>
                    <?php echo $this->form()->closeTag($commissioningSetupForm); ?>
                    <div class="space20"></div>
                    <table class="table table-bordered table-striped" id="tbl_status">
                        <thead>
                        <tr>
                            <th colspan="5">Branch Drawings</th>
                        </tr>
                        <tr>
                            <td colspan="5">Branch drawings need to be linked to the consumed drawing information.  Below are displayed the drawings that have been uploaded from the branch telemetry system.  To link an image to
                                a drawing click on the upload button.  To de-activate a drawing click on the cross button.  To activate a drawing click on the tick button.</td>
                        </tr>
                        <tr>
                            <th>Name</th>
                            <th>Width</th>
                            <th>Height</th>
                            <th style="width: 120px">Active</th>
                            <th style="width: 120px">Options</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        if ($drawings) {
                            foreach ($drawings as $drawing) {
                                echo '<tr data-drawing-id="' . $drawing->getDrawingID() . '" data-project-id="' . $project->getProjectId() . '" data-client-id="' . $project->getClient()->getClientId() . '">' .
                                    '<td>' . $drawing->getDrawing() . '</td>' .
                                    '<td>' . $drawing->getWidth() . 'px</td>' .
                                    '<td>' . $drawing->getHeight() . 'px</td>' .
                                    '<td>' . ($drawing->isActivated() ? 'Yes' : 'No') . '</td>' .
                                    '<td><button class="btn btn-primary btn-small upload-drawing-image pull-left" title="Upload image" style="margin-right: 4px"><i class="icon-upload-alt"></i></button> ' .
                                        '<button title="Deactivate image" class="btn btn-danger btn-small deactivate-drawing-image pull-left" style="margin-right: 4px; display: ' . ($drawing->isActivated() ? 'block' : 'none') . '"><i class="icon-remove"></i></button> ' .
                                        '<button title="Activate image" class="btn btn-success btn-small activate-drawing-image pull-left"  style="margin-right: 4px; display: ' . (!$drawing->isActivated() ? 'block' : 'none') . '"><i class="icon-check"></i></button>' .
                                    '</td>' .
                                    '</tr>';
                            }
                        } else {
                            echo '<tr><td colspan="5">There are no drawings assigned to the current project and/or branch</td></tr>';
                        }
                        ?>
                        </tbody>
                    </table>

                    <div class="space20"></div>
                    <table class="table table-bordered" >
                        <thead>
                        <tr>
                            <th>Branch Devices</th>
                        </tr>
                        <tr>
                            <td>Below are displayed the devices that have been detected and loaded from the selected linked branch.</td>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <table class="table table-bordered table-striped" id="tbl_devices" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/commissioningsavedevicetype/">
                                    <thead>
                                    <tr>
                                        <th>Serial</th>
                                        <th>Emergency</th>
                                        <th>Floor</th>
                                        <th style="width: 300px">Type</th>
                                        <th style="width: 200px">Options</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    if ($devices) {
                                        foreach ($devices as $device) {
                                            $deviceType = ($device->getType() ? $device->getType()->getName() : 'Undefined');
                                            $deviceTypeId = ($device->getType() ? $device->getType()->getDeviceTypeID() : '');
                                            echo '<tr>' .
                                                '<td>' . $device->getDeviceSN() . '</td>' .
                                                '<td>' . ($device->isIsE3() ? 'Yes' : 'No') . '</td>' .
                                                '<td>' . $device->getDrawing()->getDrawing(true) . '</td>' .
                                                '<td data-device-id="' . $device->getDeviceID() . '" data-device-type-id="' . $deviceTypeId . '" data-device-type-label="' . ($deviceType ? $deviceType : 'Undefined') . '">' . $deviceType . '</td>' .
                                                '<td>' .
                                                '<button class="btn btn-small btn-primary btn-edit-device-type"><i class="icon-edit"></i> Edit</button>' .
                                                '<button style="display: none" class="btn btn-small btn-success btn-save-device-type"><i class="icon-save"></i> Save</button> ' .
                                                '<button style="display: none" class="btn btn-small btn-danger btn-cancel-device-type"><i class="icon-remove"></i> Cancel</button>' .
                                                '</td>' .
                                                '</tr>';
                                        }
                                    } else {
                                        echo '<tr><td colspan="5">There are no devices assigned/uploaded to the current branch</td></tr>';
                                    }
                                    ?>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <select id="sel-device-types" style="display: none">
                        <option value="">Undefined</option>
                    <?php
                        foreach ($deviceTypes as $deviceType) {
                            echo '<option value="' . $deviceType->getDeviceTypeID() . '">' . $deviceType->getName() . '</option>';
                        }
                    ?>
                    </select>

                    <div class="space20"></div>
                    <form name="frmSaveStatus" id="frmSaveStatus" class="form-nomargin" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/commissioningsavestatus/">
                        <table class="table table-bordered table-striped" id="tbl_status">
                            <thead>
                            <tr>
                                <th colspan="2">Commissioning State</th>
                            </tr>
                            <tr>
                                <td colspan="2">The commissioning state options determine the appearance and status of the branches on the customer portal.</td>
                            </tr>
                            <tr>
                                <th style="width: 250px">State Name</th>
                                <th>Activated</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Head End Live</td>
                                <td><input type="checkbox" name="headend-live" <?php if ($project->hasState(20)) echo 'checked'; ?>/></td>
                            </tr>
                            <tr>
                                <td>Design Loaded</td>
                                <td><input type="checkbox" name="design-loaded" <?php if ($project->hasState(21)) echo 'checked'; ?>/></td>
                            </tr>
                            <tr>
                                <td>Marked 'As-Installed' Drawings Received</td>
                                <td><input type="checkbox" name="as-installed" <?php if ($project->hasState(22)) echo 'checked'; ?>/></td>
                            </tr>
                            <tr>
                                <td>Part Commissioned - Awaiting Signoff</td>
                                <td><input type="checkbox" name="awaiting-signoff" <?php if ($project->hasState(23)) echo 'checked'; ?>/></td>
                            </tr>
                            <tr>
                                <td>Commissioned</td>
                                <td><input type="checkbox" name="commissioned" <?php if ($project->hasState(101)) echo 'checked'; ?>/></td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="2"><button class="btn btn-primary" id="btn-save-status"><i class="icon-ok icon-white"></i> Save Status</button></td>
                            </tr>
                            </tfoot>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>