<?php
$this->headLink()
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ->appendStylesheet('/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css')
    ;
/**/
$this->inlineScript()
    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
    ->appendFile('/assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js')
    ->appendFile('/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js')
    ->appendFile('/js/forms/project/email.js')
;/**/

$this->headStyle()->captureStart() 
?>
    #mailListTbl tr:hover {
        cursor: pointer;
    } 
    #mailListTbl tr.active {
        color: #4A8BC2;
    }
    
    #mailListTbl tr.active:hover {
        color: black;
    }
    
<?php 
$this->headStyle()->captureEnd();


?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN  widget-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-reorder"></i> Project Threads</h4>
                <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="mailListLoader" class="loader"></div>
                <div class="row-fluid">
                    <div class="span6">
                        <form action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/emailthread/" id="mailListForm">
                        <table class="table table-striped table-bordered table-advance table-hover" id="mailListTbl">
                            <thead>
                            <tr>
                                <th><i class="icon-calendar"></i> When</th>
                                <th ><i class="icon-envelope"></i> Description</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td colspan="2">loading your message threads ... </td>
                            </tr>
                            </tbody>
                        </table>
                        <h5 id="mailListCount">&nbsp;</h5>
                        </form>
                    </div>
                    <div class="span6">
                        <div class="widget blue">
                            <div class="widget-body relative" style="height: 500px; overflow-x: auto; overflow-y: scroll">
                                <div id="mailItemLoader" class="loader"></div>
                                <div id="messages">
                                    <h5>Click on a thread to view messages</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END EXTRAS widget-->
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN  widget-->
        <div class="widget red">
            <div class="widget-title">
                <h4><i class="icon-reorder"></i> Send Email</h4>
                <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body form relative">
                <div id="emailLoader" class="loader"></div>
                <div id="msgs"></div>
                <?php echo $this->form()->openTag($form); ?>
                <div class="control-group">
                    <label class="control-label ">To:</label>
                    <div class="controls ">
                        <?php echo $this->formElement($form->get('to'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label ">CC:</label>
                    <div class="controls ">
                        <?php echo $this->formElement($form->get('cc'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Subject:</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('subject'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Message</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('message'));  ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag($formEmail); ?>
                <hr />
                <button class="btn btn-success" id="btn-send-email"><i class="icon-envelope"></i> Send Email</button>
            </div>
        </div>
        <!-- END EXTRAS widget-->
    </div>
</div>