<?php
$this->headLink()
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
    ->appendFile('/js/forms/project/system.js');

echo $this->partial('partial/system/csvpdfdownload.phtml');
if ($project->getRetrofit()) {
    echo $this->partial('partial/system/dialogsretrofit.phtml');
} else {    
    echo $this->partial('partial/system/dialogs.phtml');
}

?>
<div id="modalExportToProjis" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Export to Projis</h3>
    </div>
    <div class="modal-body">
        <div id="exportToProjisLoader" class="loader"></div>
        <p>
            Are you sure that you would like to export this project to Projis?<br /><br />
            Warning: this will create a supply-only project in Projis with aggregated system data in the root space.
            <form id="frmExportToProjis" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/export/projis/"></form>
        </p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-export-to-projis" aria-hidden="true"><i class="icon-ok"></i> Confirm</button>
    </div>
</div>
<div id="modalReapplyPricing" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Re-Apply Volume Discount&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="reapplyPricingLoader" class="loader"></div>
        <p>
            Are you sure that you would like to reapply the pricing for this project?<br /><br />
            Warning: this will reset the pricing of modified items and cannot be undone.
        </p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <!--<button class="btn btn-success" id="btn-confirm-reapplypricing" aria-hidden="true"><i class="icon-ok"></i> Confirm</button><!-- -->
    </div>
</div>
<div id="modalReapplyInstallation" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Re-Apply Product Installation Costs&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="reapplyInstallationLoader" class="loader"></div>
        <p>
            Are you sure that you would like to reapply the product installation costs for this project?<br /><br />
            Warning: this will reset the space-level installation costs across every space in the project.
            <form id="reapplyInstallationForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/reapplypricing/"></form>
        </p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-reapplyinstallation" aria-hidden="true"><i class="icon-ok"></i> Confirm</button>
    </div>
</div>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav metro-fix-view">

        <div class="metro-nav-block  nav-block-grey">
            <a href="#myModalSaveConfig" data-toggle="modal" href="javascript:" data-original-title="" id="btn-config-save">
                <div class="text-center">
                    <i class="icon-save"></i>
                </div>
                <div class="status">Save Config</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-blue ">
            <a href="#myModalLoadConfig" data-toggle="modal" href="javascript:" data-original-title="" id="btn-config-load">
                <div class="text-center">
                    <i class="icon-cogs"></i>
                </div>
                <div class="status">Load Config</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-green">
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/export/index/" id="btn-config-export">
                <div class="text-center">
                    <i class="icon-double-angle-right"></i>
                </div>
                <div class="status">Export Wizard</div>
            </a>
        </div>
<?php if (!empty($projisExportEnabled)) { ?>        
        <div class="metro-nav-block nav-block-yellow">
            <a href="#modalExportToProjis" data-toggle="modal" href="javascript:" data-original-title="" id="btn-export-to-projis">
                <div class="text-center">
                    <i class="icon-chevron-sign-right"></i>
                </div>
                <div class="status">Export to Projis</div>
            </a>
        </div>
<?php } ?>        
        <div class="metro-nav-block nav-block-orange">
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/export/trial/" id="btn-config-export">
                <div class="text-center">
                    <i class="icon-dropbox"></i>
                </div>
                <div class="status">Create Trial</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-purple">
            <a href="javascript:" class="btn-config-export-csv">
                <div class="text-center">
                    <i class="icon-download"></i>
                </div>
                <div class="status">Download CSV</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-red">
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/survey/" class=" ">
                <div class="text-center">
                    <i class="icon-pencil"></i>
                </div>
                <div class="status">Survey</div>
            </a>
        </div>
    </div>
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Create Space</h3>
    </div>
    <div class="modal-body">
        <div id="spaceLoader" class="loader"></div>
        <div class="widget blue">
            <div class="widget-title">
                <h4>Space Details</h4>
            </div>
            <div class="widget-body">
                <!-- BEGIN FORM-->
                <?php echo $this->form()->openTag($form); ?>
                    <div class="control-group">
                        <label class="control-label">Name</label>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('name'));  ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Building:</label>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('building'));  ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Type</label>
                        <div class="controls">
                            <?php echo $this->formElement($form ->get('spaceType'));  ?>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag($form); ?>
                <div class="alert alert-block alert-warning fade in">
                    <h4 class="alert-heading">Important!</h4>
                    <p>
                        If you need to create a new building then <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/buildingadd/">click here</a>.  Please be aware that this will navigate you away from this page during building creation.
                    </p>
                </div>
                <!-- END FORM-->
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button id="btn-create-space" class="btn btn-success"><i class="icon-plus"></i> Create Space</button>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-list"></i> Space Setup</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <div class="clearfix">
                    <div class="btn-group pull-left">
                        <button class="btn green" id="btn-create-space-dialog">
                            Add Space <i class="icon-plus"></i>
                        </button>
                    </div>
                    <div class="btn-group pull-right">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                        </button>
                       <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:" id="optReapplyPricing">Re-apply volume discounts</a></li>
                            <li><a href="javascript:" id="optReapplyInstallation">Re-apply product installation costs</a></li>
                        </ul><!-- -->
                    </div>
                </div>
                <div class="space15"></div>
                <div class="tabbable custom-tab tabs-left relative">
                    <!-- Only required for left/right tabs -->
                    <ul class="nav nav-tabs tabs-left fixed150" id="tab-building">
                        <?php
                            if (empty($buildings)){
                                echo '<li class="active disabled"><a href="#tab_3_1" data-toggle="tab">No Buildings Found</a></li>';
                            } else {
                                $cnt = 0;
                                foreach ($buildings as $building) {
                                    $cnt++;
                                    echo '<li building-id="'.$building->getBuildingId().'" building-name="'.ucwords($building->getName()).'" building-address="'.$building->getAddress()->assemble().'" class="'.(($cnt==1)?'active':'').'"><a href="#tab_3_1" data-toggle="tab">'.ucwords($building->getName()).'</a></li>';
                                }
                            }
                        ?>
                    </ul>
                    <div class="tab-content " style="<?php echo empty($buildings)?'min-height: 180px':'min-height: 440px'; ?>">
                        <div id="buildingLoader" class="loader"></div>
                        <div class="tab-pane active" id="tab_3_1">
                            <?php if (empty($buildings)){ ?>
                            <p>No spaces have been added to this project.</p>
                            <p>
                                To add a space to a project click on the &quot;Add Space&quot; button and follow the instructions.  
                                If the project that you are building is not space-driven then please use the non-space setup below.
                            </p>
                            <?php } else {?>
                            <h4 id="info-name"></h4>
                            <p id="info-address"></p>
                            <form id="SpaceListForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/">
                                <table class="table table-striped table-bordered table-advance table-hover" id="spaces_tbl">
                                    <thead>
                                        <tr>
                                            <th ><i class="icon-cog"></i> Space Name</th>
                                            <th style="width: 110px"> Products</th>
                                            <th class="hidden-phone" style="width: 130px"> Value</th>
                                            <th class="hidden-phone" style="width: 110px"> Quantity</th>
                                            <th class="hidden-phone" style="width: 130px"> Total</th>
                                            <th style="width: 120px"></th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </form>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="space10"></div>
                <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/buildingadd/"><i class="icon-building"></i> Need to create a new building? Click here <i class="icon-double-angle-right"></i></a>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-list"></i> Non-Space Setup</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="systemEditLoader" class="loader"></div>
                <div class="clearfix">
                    <div class="btn-group pull-left">
<?php if ($this->isGranted('project.write')) { ?>
                        <button id="btn-add-product" class="btn green" style="margin-right: 4px">
                            Add Product <i class="icon-plus"></i>
                        </button>
                        <button id="btn-add-service" class="btn green" style="margin-right: 4px">
                            Add Service <i class="icon-plus"></i>
                        </button>
                        <button id="btn-add-architectural" class="btn green">
                            Add Architectural <i class="icon-plus"></i>
                        </button>
<?php } ?>
                    </div>
                    <div class="btn-group pull-right">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <!--<li><a href="#">Print Space</a></li>
                            <li><a href="#">Print Full System</a></li>
                            <li class="divider" role="presentation"></li><!-- -->
                            <li><a href="javascript:" class="btn-config-export-csv" data-spaceId="<?php echo $space->getSpaceId(); ?>" data-spaceName="<?php echo $space->getName(); ?>">Export Space to CSV</a></li>
                            <li><a href="javascript:" class="btn-config-export-csv">Export Full System to CSV</a></li>
                            <li class="divider" role="presentation"></li>
                            <li><a href="javascript:" class="btn-change-hrs">Change Hours</a></li>
                        </ul><!-- -->
                    </div>
                </div>
                <div class="space15"></div>

                <table class="table table-striped table-bordered table-advance table-hover" id="products_tbl">
                    <thead>
                        <tr>
                            <th ><i class="icon-cog"></i> Product</th>
                            <th style="width: 60px">Qty</th>
                            <th style="width: 60px">Hrs <a href="javascript:" class="icon-cog btn-change-hrs"></a></th>
                            <th style="width: 60px">PPU</th>
                            <th style="width: 60px">ICPU</th>
                            <th style="width: 50px" class="hidden-phone">LUX</th>
                            <th style="width: 50px" class="hidden-phone">OCC</th>
                            <th style="width: 60px">Retrofit</th>
                            <th style="width: 120px">Options</th>
                            <th style="width: 120px">Price (inc MCD)</th>
                        </tr>
                    </thead>
                    <tbody><?php
                        $totalPriceMCD = 0;
                        $editable = $this->isGranted('project.write');

                        if (!empty($systems)) {
                            $mcd = $project->getMCD();
                            foreach ($systems as $system) {
                                $priceMCD = round($system['quantity'] * (round($system['ppu'] * (1- ($mcd * $system['mcd'])), 2)),2);
                                $totalPriceMCD+=$priceMCD;

                                $description = !empty($system['legacyId'])?'<span class="label label-success popovers" '
                                        . 'data-content="Type: '.$system['category'].
                                        '<br />Details: '.$system['description'].
                                        '<br />Quantity: '.$system['legacyQuantity'].
                                        (!empty($system['legacyWatts'])?'<br />Rating: '.$system['legacyWatts'].'W':'').
                                        (!empty($system['legacyMcpu'])?'<br />Maintenance: &#163;'.number_format($system['legacyMcpu'],2):'').'" '
                                        . 'data-html="true" '
                                        . 'data-placement="left" '
                                        . 'data-original-title="Retrofit Details" '
                                        . 'data-trigger="hover">Yes</span>':'<span class="label label-important">No</span>';
                                $title = $system['model'];
                                $content = $system['pdesc'].'<br>';
                                if (!empty($system['label'])) {
                                    $content.='<br>Label: '.$system['label'];
                                }
                                if ($system['typeId']==3){
                                    $attr = json_decode($system['attributes'], true);
                                    $config = '';
                                    foreach ($attr['dConf'] as $icnf) {
                                        $config.='<br>';
                                        foreach ($icnf as $cnf=>$qtty) {
                                            for ($k=0; $k<$qtty; $k++) {
                                                $config.='['.$cnf.']';
                                            }
                                        }
                                    }
                                    $content.='<br>Specified: '.$attr['sLen'].'mm<br >Achievable: '.$attr['dLen'].'mm<br>Units: '.(empty($attr['dUnits'])?1:$attr['dUnits']).'<br>'.$config;
                                }
                                echo '<tr>'
                                    . '<td>'.$system['model'].' <i class="icon-info-sign popovers" data-trigger="hover" data-html="true" data-placement="top" data-content="'.$content.'" data-original-title="'.$title.'"></i></td>'
                                    . '<td class="row-right">'.$system['quantity'].'</td>'
                                    . '<td class="row-right hidden-phone" class="row-right">'.$system['hours'].'</td>'
                                    . '<td class="row-right">'.$system['ppu'].'</td>'
                                    . '<td class="row-right">'.$system['ippu'].'</td>'
                                    . '<td class="hidden-phone">'.$system['lux'].'%</td>'
                                    . '<td class="hidden-phone">'.$system['occupancy'].'%</td>'
                                    . '<td>'.$description.'</td>'
                                    . '<td><div style="width:120px">'
                                        .($system['locked']?'locked':'<button class="btn btn-primary action-system-edit" data-systemid="'.$system['systemId'].'"><i class="icon-pencil"></i></button>&nbsp;' 
                                        . '<button class="btn btn-success action-system-copy" data-systemid="'.$system['systemId'].'"><i class="icon-copy"></i></button>&nbsp;'
                                        . ($editable?'<button class="btn btn-danger action-system-delete" data-systemid="'.$system['systemId'].'"><i class="icon-remove"></i></button>&nbsp;':''))
                                        . '</td></div>'
                                    . '<td class="row-right">&#163;'.number_format($priceMCD,2).'</td>'
                                    . '</tr>';
                            }
                        }
                    
                    ?></tbody>
                    <tfoot>
                        <tr>
                            <th colspan="9">Total Price</th>
                            <th class="row-right">&#163;<?php echo number_format($totalPriceMCD,2); ?></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
<div id="myModalSaveConfig" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel2">Save Configuration</h3>
    </div>
    <div class="modal-body relative">
        <div id="saveConfigLoader" class="loader"></div>
        <p>To save the current configuration enter the details below and click on the Save button.</p>
        <p>Saved configurations can be retrieved at any time but please note that retrieval will over-write current configuration</p>
        <div class="widget-body">
            <!-- BEGIN FORM-->
            <form class="form-horizontal" id="formSaveConfig" name="formSaveConfig" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/configsave/">
                <div class="control-group">
                    <label class="control-label">Save Name:</label>
                    <div class="controls">
                        <input type="text" value="" placeholder="not required" class="input" name="name" >
                    </div>
                </div>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" aria-hidden="true" id="btnSaveConfig">Save Configuration</button>
        <button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>
<div id="myModalLoadConfig" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel2">Load Configuration</h3>
    </div>
    <div class="modal-body relative">
        <div id="loadConfigLoader" class="loader"></div>
        <p>Select configuration from the drop-down list and click on the load button.</p>
        <div class="alert alert-block alert-warning fade in">
            <h4 class="alert-heading">Important Note</h4>
            <p>
                The current configuration will automatically be saved before new configuration is loaded unless you un-check the auto save option.
            </p>
        </div>
        <div class="widget-body">
            <!-- BEGIN FORM-->
            <form class="form-horizontal" id="formLoadConfig" name="formLoadConfig" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/configload/">
                <div class="control-group">
                    <label class="control-label">Configuration<span id="refresh-config" class="add-on" style="margin-left: 5px;"><i class="icon-refresh"></i></span></label>
                    <div class="controls">
                        <select class="span12" name="saveId">
                            <option>Please Select</option>
                            <?php
                            if (!empty($saves)) {
                                foreach ($saves as $save) {
                                    $name = $save['created']->format('jS F Y H:i:s').(empty($save['name'])?'':' - '.$save['name']).' - ['.$save['saveId'].']';
                                    echo '<option value="'.$save['saveId'].'">'.$name.'</option>';
                                }
                            }
                            
                            ?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Auto Save</label>
                    <div class="controls">
                        <div id="transition-percent-toggle-button">
                            <input type="checkbox" checked="checked" name="autoSave">
                        </div>
                    </div>
                </div>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-info" aria-hidden="true" id="btnLoadConfig">Load Configuration</button>
        <button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
</div>
<div id="modalCopySpace" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Duplicate Space Confirmation&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="spaceCopyLoader" class="loader"></div>
        <p>
            Are you sure that you would like to duplicate the selected space?<br />
            Please note: the item will be an exact copy and may require editing.<br /><br />
        </p>
        <form id="frmCopySpace" class="form-horizontal" action="<?php echo '/client-'.$project->getClient()->getClientId().'/project-'.$project->getProjectId().'/copyspace/'; ?>">
            <input type="hidden" name="spaceId" value="" />
            <div class="control-group">
                <label class="control-label">New Space Name</label>
                <div class="controls">
                    <input type="text" class="span12" name="newSpaceName" value="" />
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-copy-space" aria-hidden="true"><i class="icon-ok"></i> Confirm</button>
    </div>
</div>
<div id="modalDeleteSpace" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Delete Space Confirmation&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="spaceDeleteLoader" class="loader"></div>
        <p>
            Are you sure that you would like to delete the selected space:<br />
        </p>
        <form id="frmDeleteSpace" class="form-horizontal" action="<?php echo '/client-'.$project->getClient()->getClientId().'/project-'.$project->getProjectId().'/deletespace/'; ?>">
            <input type="hidden" name="spaceId" value="" />
            <div class="control-group">
                <label class="control-label">Space Name</label>
                <div class="controls">
                    <input id="delSpaceName" disabled="disabled" class="span12" />
                </div>
            </div>
        </form>
        <p>
            Please note: you can save config before deletion if required
        </p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-delete-space" aria-hidden="true"><i class="icon-ok"></i> Confirm</button>
    </div>
</div>