<?php
$this->headLink()
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/signalr/jquery.signalr-1.1.2.min.js')
    ->appendFile('https://testing.wattzo.com/api/realtime/hubs')
    ->appendFile('https://www.google.com/jsapi')
        
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')

    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
        
    ->appendFile('/assets/flot/jquery.flot.js')
    ->appendFile('/assets/flot/jquery.flot.resize.js')
    ->appendFile('/assets/flot/jquery.flot.pie.js')
    ->appendFile('/assets/flot/jquery.flot.stack.js')
    ->appendFile('/assets/flot/jquery.flot.crosshair.js')
    ->appendFile('/js/forms/project/telemetry.js')
/**/;


    $items = array (
        '01-166-542f85'=>array (
            'name'=>'Short LED board 1',
            'switch'=>false
        ),
        '01-166-258ce3'=>array (
            'name'=>'Twin 5ft Vapour Seal',
            'switch'=>false
        ),
        '01-166-0b9275'=>array (
            'name'=>'1200 x 600 Desk',
            'switch'=>false
        ),
        '01-166-56bc89'=>array (
            'name'=>'1200 x 600 (Switched)',
            'switch'=>true
        ),
        /*'01-166-3dcd1f'=>array (
            'name'=>'PIR (not allocated)',
            'switch'=>true
        ),/**/
    );
    
    $switches = array(
        /*'01-166-3dcd1f' => array(
            "01-166-542f85"=>true, 
            "01-166-258ce3"=>true
        ),/**/
        '01-166-56bc89' => array (
            '01-166-0b9275'=>true
        )
    );

?>
<style>
    .onoff-toggle-mask {
        position: absolute; 
        left: 0; 
        top: 0; 
        z-index: 999; 
        background-color: #fff; 
        width: 100%; 
        height: 100%; 
        opacity: 0.8; 
        display: block; 
        text-align: center;
    }
    
    .onoff-toggle-mask span {
        margin-top: 12px;
        display: inline-block;
    }
    
    #devices tbody td {
        vertical-align: middle;
    }
</style>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-error">
            <strong>Important Notice:</strong> telemetry as displayed below is for demonstrative purposes only .
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <!-- BEGIN INTERACTIVE CHART PORTLET-->
        <div class="widget yellow">
            <div class="widget-title">
                <h4><i class="icon-tablet"></i> Hub: 01-001-ABC123</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <table class="table table-bordered table-striped" id="devices">
                    <thead>
                    <tr>
                        <th>Device</th>
                        <th>Details</th>
                        <th>Power</th>
                        <th style='width: 100px'>Control</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($items as $iid=>$item) {
                        echo '<tr data-device="'.$iid.'" data-state="ready" data-switch="'.($item['switch']?'1':'0').'">
                        <td>'.$iid.' <i class="icon-lightbulb"></i>
                        </td>
                        <td class="deviceGroup">'.$item['name'].'</td>
                        <td class="deviceWatts"><span class="badge badge-important">0w</span></td>
                        <td class="relative">
                            <div class="controls">
                                <div class="onoff-toggle">
                                    <input class="onoff" type="checkbox" />
                                </div>
                            </div>
                            <div class="onoff-toggle-mask">
                                <span>connecting ...</span>
                            </div>
                        </td>
                    </tr>';
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END INTERACTIVE CHART PORTLET-->
    </div>
    <div class="span6">
        <!-- BEGIN INTERACTIVE CHART PORTLET-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-bar-chart"></i> Live Power Gauge</h4>
            <span class="tools">
            <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <div id="chart_div" style="margin: auto; width: 240px; height: 240px;"></div>
            </div>
        </div>
        <!-- END INTERACTIVE CHART PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN INTERACTIVE CHART PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-bar-chart"></i> Historic Power Meter</h4>
            <span class="tools">
            <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <div id="chart-telemetry" class="chart"></div>
            </div>
        </div>
        <!-- END INTERACTIVE CHART PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN INTERACTIVE CHART PORTLET-->
        <div class="widget red">
            <div class="widget-title">
                <h4><i class="icon-list-alt"></i> Rules</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Trigger</th>
                            <th>Activates</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            $itemOpts = array();
                            foreach ($items as $iid=>$item) {
                                if (!empty($item['switch'])) {
                                    continue;
                                }
                                $itemOpts[$iid] = $item;
                            }
                            foreach ($items as $iid=>$item) {
                                if (empty($item['switch'])) {
                                    continue;
                                }
                                
                                echo '<tr>
                            <td>'.$item['name'].' ('.$iid.')</td>
                            <td><select style="width: 450px" data-switch="'.$iid.'" class="chzn-select ruleoptions" multiple="multiple" id="opts-'.$iid.'">';
                                foreach ($itemOpts as $i=>$v) {
                                    echo '<option value="'.$i.'" '.(empty($switches[$iid][$i])?'':'SELECTED').'>'.$v['name'].'</option>';
                                }
                            echo '</select></td>
                        </tr>';
                            }
                        
                        ?>
                        
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END INTERACTIVE CHART PORTLET-->
    </div>
</div>
