<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>RBS - Commissioning Sheet - <?php echo $project->getName(); ?></title>

    <?php
    echo $this->partial('partial/project/docs/css.phtml');
    ?>

</head>
<body>
<?php
//if (!empty($footer['pages'])) {
//    echo $this->partial('partial/project/docs/pages.phtml');
//}
echo $this->partial('partial/project/docs/footers/8p3logo.phtml');
?>
<style>
    #letterhead_logo {
        width: 240px;
        position: absolute;
        right: 0;
        top: 0;
    }

    #nb {
        margin-top: 10px;
        font-size: 9pt;
    }

    .nbStar {
        position: absolute;
        right: 10px;
    }

    table  {
        border-collapse: collapse;
    }

    table thead th {
        background-color: #f3f3f3;
    }

    td, th {
        border: 1px #ccc solid;
        padding: 2px;
        margin: 0;
        position: relative;
    }

    table .center {
        text-align: center;
    }

    table .left {
        text-align: left;
    }

    table .right {
        text-align: right;
    }
</style>
<?php
echo '<img id="letterhead_logo" src="'. $resourcesUri .'img/lumitel/lumitel-lite-lowres.png" />';
?>
<h1>Emergency Lighting Commissioning Certificate</h1>
<h3><?php echo $project->getName(); ?></h3>
<p>Address: <?php echo $project->getAddress()->assemble(); ?></p>
    <table id="reportTable" width="100%">
    <thead>
    <tr>
        <th style="width: 80px">Floor ID</th>
        <th>Floor Name</th>
        <th style="width: 80px">Fixture<br>Serial</th>
        <th style="width: 80px">Test Type C,M,A<span class="nbStar">*</span></th>
        <th style="width: 90px">Installed</th>
        <th style="width: 90px">Tested</th>
        <th style="width: 80px">Passed</th>
        <th style="width: 80px">Failure<br>Code<span class="nbStar">**</span></th>
    </tr>
    </thead>
    <tbody>
    <?php
    $totalPassed = 0;
    $totalFailed = 0;
    $installed = $project->getInstalled()->format('d/m/Y');
    $commissioned = $project->getInstalled()->modify('+2 day')->format('d/m/Y');
    foreach($devices as $device) {
        $failed = $device->getStatus() && $device->getStatus()->isFault();
        if ($failed) {
            $totalFailed ++;
        } else {
            $totalPassed ++;
        }
        echo '<tr>
        <td class="center">' . $device->getDrawing()->getDrawingID() . '</td>
        <td class="center">' . $device->getDrawing()->getDrawing(true) . '</td>
        <td class="center">' . $device->getDeviceSN() . '</td>
        <td class="center">C</td>
        <td class="center">' . $installed . '</td>
        <td class="center">' . $commissioned . '</td>
        <td class="center">' . ($failed ? 'N' : 'Y') . '</td>
        <td class="center">' . ($failed ? $device->getStatus()->getDeviceStatusId() : '') . '</td>
    </tr>';
    }
    ?>
    </tbody>
    <tfoot>
    <tr>
        <th colspan="8" class="left">&nbsp;</th>
    </tr>
    <tr>
        <th colspan="7" class="left">&nbsp;Total Devices</th>
        <th><?php echo ($totalPassed + $totalFailed); ?></th>
    </tr>
    <tr>
        <th colspan="7" class="left">&nbsp;Total Devices Passed</th>
        <th><?php echo ($totalPassed); ?></th>
    </tr>
    <tr>
        <th colspan="7" class="left">&nbsp;Total Devices Failed</th>
        <th><?php echo ( $totalFailed); ?></th>
    </tr>
    </tfoot>
</table>
<div id="nb">
    * Test type codes: C = commission, M = monthly, A = Annual <br>
    ** Failure Codes: <?php
    if ($faultCodes) {
        $codes = array();
        foreach ($faultCodes as $faultCode) {
            $codes[] = $faultCode->getDeviceStatusId() . ' = ' . $faultCode->getDescription();
        }
        echo implode(', ', $codes);
    }
?>
</div>

</body>
</html>
