<?php
$this->headLink()
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css')
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ->appendStylesheet('/assets/dropzone/css/basic.css')
    ->appendStylesheet('/assets/dropzone/css/dropzone.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/assets/dropzone/dropzone.js')
    ->appendFile('/js/forms/space/edit.js?20150319');



$this->inlineScript()->captureStart();
echo <<<JS
<!-- 3 -->
Dropzone.options.myDropzone = {
    acceptedFiles: 'image/*',
    thumbnailWidth:null,
    thumbnailHeight:null,
    //addRemoveLinks: true,
    init: function() {
        thisDropzone = this;
        
        <!-- 4 -->
        $.get('/client-{$project->getClient()->getClientId()}/project-{$project->getProjectId()}/document/list/?subid={$space->getSpaceId()}&category=10&dropzone=1', function(data) {
 
            <!-- 5 -->
            $.each(data, function(key,value){
                 
                var mockFile = { name: value.name, size: value.size };
                 
                thisDropzone.options.addedfile.call(thisDropzone, mockFile);
                thisDropzone.options.thumbnail.call(thisDropzone, mockFile, "/client-{$project->getClient()->getClientId()}/project-{$project->getProjectId()}/document/download/?documentListId="+value.dlid);
                
                 
            });/**/
             
        });
    },
    accept: function(file, done) {
        //console.log(file);
        if (file.type != "image/jpeg" && file.type != "image/png") {
            done("Error! Files of this type are not accepted");
        }
        else { done(); }
    }
};
                
$(function() {
    
});
JS;
$this->inlineScript()->captureEnd();

if ($project->getRetrofit()) {
    echo $this->partial('partial/system/dialogsretrofit.phtml');
} else {    
    echo $this->partial('partial/system/dialogs.phtml');
}

?>
<div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Create Space</h3>
    </div>
    <div class="modal-body">
        <div id="spaceNewLoader" class="loader"></div>
        <div class="widget blue">
            <div class="widget-title">
                <h4>Space Details</h4>
            </div>
            <div class="widget-body">
                <!-- BEGIN FORM-->
                <?php echo $this->form()->openTag($form); ?>
                    <div class="control-group">
                        <label class="control-label">Name</label>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('name'));  ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Building:</label>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('building'));  ?>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag($form); ?>
                <div id="msgs4"></div>
                <!-- END FORM-->
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button id="btn-create-space" class="btn btn-success"><i class="icon-plus"></i> Create Space</button>
    </div>
</div>
<div id="myModal4" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Add Note&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="noteLoader" class="loader"></div>
        <p>
            Enter the note that you would like to add to the space in the box provided and then click on the Add Note button.
        </p>
        <div class="control-group">
        <form id="AddNoteForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/space-<?php echo $space->getSpaceId(); ?>/addnote/">
            <div class="controls">
                <textarea class="span12" name="note" placeholder="enter your note here"></textarea>
            </div>
        </form>
        </div>   
        <div id="msgs3"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-save-note" aria-hidden="true"><i class="icon-plus"></i> Add Note</button>
    </div>
</div>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav metro-fix-view">

        <div class="metro-nav-block  nav-block-grey">
            <a href="<?php echo $this->url('project', array('action'=>'system', 'cid'=>$project->getClient()->getClientId(), 'pid'=>$project->getProjectId())); ?>">
                <div class="text-center">
                    <i class="icon-sitemap"></i>
                </div>
                <div class="status">Back To Setup</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-green ">
            <a href="javascript: location.reload();">
                <div class="text-center">
                    <i class="icon-refresh"></i>
                </div>
                <div class="status">Reload Page</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-purple">
            <a data-spaceId="<?php echo $space->getSpaceId(); ?>" data-spaceName="<?php echo $space->getName(); ?>" href="javascript:" class="btn-config-export-csv">
                <div class="text-center">
                    <i class="icon-download"></i>
                </div>
                <div class="status">Download CSV</div>
            </a>
        </div>
<?php if (!empty($spacePrev)) { ?>        
        <div class="metro-nav-block  nav-block-blue">
            <a href="<?php echo $this->url('space', array('action'=>'index', 'cid'=>$project->getClient()->getClientId(), 'pid'=>$project->getProjectId(), 'sid'=>$spacePrev['spaceId'])); ?>">
                <div class="text-center">
                    <i class="icon-double-angle-left"></i>
                </div>
                <div class="status">Previous Space</div>
            </a>
        </div>
<?php } ?>        
<?php if (!empty($spaceNext)) { ?>        
        <div class="metro-nav-block  nav-block-blue">
            <a href="<?php echo $this->url('space', array('action'=>'index', 'cid'=>$project->getClient()->getClientId(), 'pid'=>$project->getProjectId(), 'sid'=>$spaceNext['spaceId'])); ?>">
                <div class="text-center">
                    <i class="icon-double-angle-right"></i>
                </div>
                <div class="status">Next Space</div>
            </a>
        </div>
<?php } ?>
        <div class="metro-nav-block  nav-block-orange">
            <a href="javascript:" id="btn-create-space-dialog">
                <div class="text-center">
                    <i class="icon-plus-sign"></i>
                </div>
                <div class="status">New Space</div>
            </a>
        </div>
    </div>
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<div class="row-fluid">
    <div class="span12 ">
        <form id="DeleteNoteForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/space-<?php echo $space->getSpaceId(); ?>/deletenote/">
        <div class="alert alert-info relative" id="space-notes">
            <div id="noteDeleteLoader" class="loader"></div>
            <button class="close" id="btn-add-note">+</button>
<?php 
$notes = $space->getNotes();
$cnt = 0;
if (!empty($notes)) {
    $notesArr  = json_decode($notes, true);
    if (!empty($notesArr)) {
?>
<?php
        foreach ($notesArr as $idx=>$note) {
            $cnt++;
            echo "<div class=\"note\"><strong>Note:</strong> {$note} <a data-index=\"{$idx}\" href=\"javascript:\" class=\"delete-note\"><i class=\"icon-remove\"></i></a></div>";
            //echo (($cnt>1)?'<br />':'')."<strong>Note {$cnt}:</strong> {$note}. <a href=\"javascript:\"><i class=\"icon-remove\"></i></a>";
        }
?>
<?php
    } 
}

if ($cnt==0) {
    echo '<div  id="nonote">No notes added to space</div>';
}
?>
        </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-cog"></i> Space Details</h4>
                            <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                            </span>
            </div>
            <div class="widget-body relative">
                <div id="spaceLoader" class="loader"></div>
                <?php echo $this->form()->openTag($formSpace); ?>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <label class="control-label">Name</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('name'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Quantity</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('quantity'));  ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <label class="control-label">Building</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('building'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Type</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('spaceType'));  ?>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="javascript:" id="btnShowMoreSpaceDetails">View additional space details <i class="icon-double-angle-right"></i></a>
                <a href="javascript:" id="btnHideMoreSpaceDetails" style="display: none">Hide additional space details <i class="icon-double-angle-left"></i></a>
                <hr />
                <div class="row-fluid" id="spaceMoreDetails" style="display: none">
                    <div class="span6">
                        <div class="control-group">
                            <label class="control-label">Floor</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('floor'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Room Length (m)</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('dimy'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Room Width (m)</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('dimx'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Ceiling Type</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('ceiling'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Tile Size (mm)</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('tileSize'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Void Dimension (mm)</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('voidDimension'));  ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <label class="control-label">Grid Type</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('grid'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Ceiling Height (m)</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('dimh'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Tile Measurement</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('metric'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Tile Type</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('tileType'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Elec Conn</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('electricConnector'));  ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Lux Level (LUX)</label>
                            <div class="controls">
                                <?php echo $this->formElement($formSpace->get('luxLevel'));  ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag($formSpace); ?>
                <div id="msgs2"></div>
                Created <?php echo $space->getCreated()->format('l jS F Y \a\t\ H:i');  ?>
                <button class="btn btn-default" id="btn-update-space" style="float: right"><i class="icon-edit icon-white"></i> Update</button>
                <button class="btn btn-default" id="btn-refresh-space" style="float: right; margin-right: 6px"><i class="icon-refresh icon-white"></i> Refresh</button>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>

<div class="row-fluid">
    <div class="span12" id="right_column">
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-reorder"></i> Products and Services</h4>
                            <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                            </span>
            </div>
            
            <div class="widget-body relative">
                <div id="systemEditLoader" class="loader"></div>
                <div>
                    <div class="clearfix">
                        <div class="btn-group pull-left">
<?php if ($this->isGranted('project.write')) { ?>
                            <button id="btn-add-product" class="btn green" style="margin-right: 4px">
                                Add Product <i class="icon-plus"></i>
                            </button>
                            <button id="btn-add-service" class="btn green" style="margin-right: 4px">
                                Add Service <i class="icon-plus"></i>
                            </button>
                            <button id="btn-add-architectural" class="btn green">
                                Add Architectural <i class="icon-plus"></i>
                            </button>
<?php } ?>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:" class="btn-config-export-csv" data-spaceId="<?php echo $space->getSpaceId(); ?>" data-spaceName="<?php echo $space->getName(); ?>">Export Space to CSV</a></li>
                                <li><a href="javascript:" class="btn-config-export-csv">Export Full System to CSV</a></li>
                                <li class="divider" role="presentation"></li>
                                <li><a href="javascript:" class="btn-change-hrs">Change Hours</a></li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="space15"></div>
                    <table class="table table-striped table-hover table-bordered table-row-middle" id="system_tbl">
                        <thead>
                        <tr>
                            <th >Product</th>
                            <th style="width: 60px">Qty</th>
                            <th style="width: 60px">Hrs <a href="javascript:" class="icon-cog btn-change-hrs"></a></th>
                            <th style="width: 60px">PPU</th>
                            <!--<th style="width: 60px">ICPU</th><!-->
                            <th style="width: 50px" class="hidden-phone">LUX</th>
                            <th style="width: 50px" class="hidden-phone">OCC</th>
                            <th style="width: 60px">Retrofit</th>
                            <th style="width: 120px">Options</th>
                            <th style="width: 120px">Price (inc MCD)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php 
                            $totalPriceMCD = 0;
                            $totalPriceMCDQuantity = 0;
                            $editable = $this->isGranted('project.write');
                            if (!empty($systems)) {
                                $duplication = empty($space->getQuantity()) ? 1 : $space->getQuantity();
                                $mcd = $project->getMCD();
                                foreach ($systems as $system) {
                                    $priceMCD = round($system['quantity'] * (round($system['ppu'] * (1-($mcd*$system['mcd'])), 2)),2);
                                    $totalPriceMCD+=$priceMCD;
                                    $totalPriceMCDQuantity += round($system['quantity'] * $duplication * (round($system['ppu'] * (1-($mcd*$system['mcd'])), 2)),2);
                                    
                                    $description = !empty($system['legacyId'])?'<span class="label label-success popovers" '
                                            . 'data-content="Type: '.$system['category'].
                                            '<br />Details: '.$system['description'].
                                            '<br />Quantity: '.$system['legacyQuantity'].
                                            (!empty($system['legacyWatts'])?'<br />Rating: '.$system['legacyWatts'].'W':'').
                                            (!empty($system['legacyMcpu'])?'<br />Maintenance: &#163;'.number_format($system['legacyMcpu'],2):'').'" '
                                            . 'data-html="true" '
                                            . 'data-placement="left" '
                                            . 'data-original-title="Retrofit Details" '
                                            . 'data-trigger="hover">Yes</span>':'<span class="label label-important">No</span>';
                                    $title = $system['model'];
                                    $content = $system['pdesc'].'<br>';
                                    if (!empty($system['label'])) {
                                        $content.='<br>Label: '.$system['label'];
                                    }
                                    if ($system['typeId']==3){
                                        $attr = json_decode($system['attributes'], true);
                                        $config = '';
                                        foreach ($attr['dConf'] as $icnf) {
                                            $config.='<br>';
                                            foreach ($icnf as $cnf=>$qtty) {
                                                for ($k=0; $k<$qtty; $k++) {
                                                    $config.='['.$cnf.']';
                                                }
                                            }
                                        }
                                        $content.='<br>Specified: '.$attr['sLen'].'mm<br >Achievable: '.$attr['dLen'].'mm<br>Units: '.(empty($attr['dUnits'])?1:$attr['dUnits']).'<br>'.$config;
                                    }
                                    echo '<tr>'
                                        . '<td>'.$system['model'].' <i class="icon-info-sign popovers" data-trigger="hover" data-html="true" data-placement="top" data-content="'.$content.'" data-original-title="'.$title.'"></i></td>'
                                        . '<td class="row-right">'.$system['quantity'].'</td>'
                                        . '<td class="row-right hidden-phone" class="row-right">'.$system['hours'].'</td>'
                                        . '<td class="row-right">'.$system['ppu'].'</td>'
                                        //. '<td class="row-right">'.$system['ippu'].'</td>'
                                        . '<td class="hidden-phone">'.$system['lux'].'%</td>'
                                        . '<td class="hidden-phone">'.$system['occupancy'].'%</td>'
                                        . '<td>'.$description.'</td>'
                                        . '<td><div style="width:120px">'
                                            . (!$system['locked']?'<button class="btn btn-primary action-system-edit" data-systemid="'.$system['systemId'].'"><i class="icon-pencil"></i></button>&nbsp;'
                                            . '<button class="btn btn-success action-system-copy" data-systemid="'.$system['systemId'].'"><i class="icon-copy"></i></button>&nbsp;'
                                            . ($editable?'<button class="btn btn-danger action-system-delete" data-systemid="'.$system['systemId'].'"><i class="icon-remove"></i></button>&nbsp;':''):'locked')
                                            . '</div></td>'
                                        . '<td class="row-right">&#163;'.number_format($priceMCD,2).'</td>'
                                        . '</tr>';
                                }
                            }
                            
                        ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th colspan="8">Space Price</th>
                            <th class="row-right">&#163;<?php echo number_format($totalPriceMCD,2); ?></th>
                        </tr>
                        <tr>
                            <th colspan="8">Total Price (space quantity of <?php echo $duplication; ?>)</th>
                            <th class="row-right">&#163;<?php echo number_format($totalPriceMCDQuantity,2); ?></th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-camera"></i> Photos</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <form action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/upload/?category=10&space=<?php echo $space->getSpaceId(); ?>" class="dropzone" id="my-dropzone"></form>
                <!--<form action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/filemanagerupload/" class="dropzone" id="my-awesome-dropzone"></form><!-- -->

            </div>
        </div>
    </div>
</div>
<?php echo $this->partial('partial/system/csvpdfdownload.phtml'); ?>
