<?php
/*
$this->headLink()
    ->appendStylesheet('/assets/nestable/jquery.nestable.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/nestable/jquery.nestable.js');

/**/


echo $this->partial('partial/system/modelnav.phtml', array('navRoute'=>'breakdown', 'project'=>$project));
?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-sitemap"></i> Space Breakdown</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <?php
                if (!empty($breakdown)) {
                    foreach ($breakdown as $buildingId => $building) {
                ?>
                <div class="space15"></div>
                <table class="table table-striped table-bordered table-advance">
                    <thead>
                        <tr>
                            <th>
                                Building: <?php echo ucwords($building ['name']); ?>
                                    <a href="javascript:;" class="icon-chevron-down"></a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                    <?php 
                        foreach ($building ['spaces'] as $spaceId => $space) {
                    ?>
                                <div class="alert alert-success">
                                    <strong>Space: <?php echo ucwords ($space ['name']); if (empty($space ['root'])) echo ' x ', $space ['quantity']; ?></strong>
                                </div>
                                <table class="table table-striped table-bordered table-advance">
                                    <thead>
                                        <tr>
                                            <th class="">Product</th>
                                            <th class="">Qty</th>
                                            <th class="">Hrs</th>
                                            <th class="">Legacy</th>
                                            <th class="">Pwr Save</th>
                                            <th class="">kW Save</th>
                                            <th class="">Saving</th>
                                            <th class="hidden-480">CO<sub>2</sub> Save</th>
                                            <th class="row-right">Total Cost</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                            foreach ( $space['products'] as $systemId => $system) {
                                ?>
                                        <tr>
                                            <td class=""><?php echo ucwords ($system [4]); ?></td>
                                            <td class=""><?php echo $system [5]; ?></td>
                                            <td class=""><?php echo $system [6]; ?></td>
                                            <td class=""><?php echo empty($system [8])?'-':ucwords($system [8]); ?></td>
                                            <td class=""><?php echo $system [12]; ?></td>
                                            <td class=""><?php echo $system [15]; ?></td>
                                            <td class=""><?php echo number_format($system [13], 2); ?></td>
                                            <td class="hidden-480"><?php echo $system [14]; ?></td>
                                            <td class="row-right"><?php echo number_format($system [1],2); ?></td>
                                        </tr>
                                <?php
                            }
                                ?>
                                    </tbody>  
                                </table>
                                <br class="clearfix" />
                    <?php
                        }
                    ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
                        <?php
                    }
                }
                
                ?>
                
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
