<?php 
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css')
    ->appendStylesheet('/assets/bootstrap-datepicker/css/datepicker.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/assets/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile('/js/forms/job/deliverynote.js')
/**/;

$this->inlineScript()->captureStart();
echo <<<JS

    var tbDeliveryNote = $('#deliverynote_tbl').dataTable({
        sDom: "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
        sPaginationType: "bootstrap",
        oLanguage: {
            sLengthMenu: "_MENU_ records per page",
            oPaginate: {
                sPrevious: "Prev",
                sNext: "Next"
            }
        },
        bProcessing: true,
        bServerSide: true,
        iDisplayLength:5,
        aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
        aoColumns: [
            null,
            { 'bSortable': true, "sClass": "hidden-phone" },
            null,
            { 'bSortable': true, "sClass": "hidden-phone" },
            null,
            { "sClass": "hidden-phone" },
            { 'bSortable': false },
        ],
        sAjaxSource: "/client-{$project->getClient()->getClientId()}/job-{$project->getProjectId()}/deliverynotelist/"
    });    

    jQuery('#deliverynote_tbl_wrapper .dataTables_filter input').addClass("input-medium"); // modify table search input
    jQuery('#deliverynote_tbl_wrapper .dataTables_length select').addClass("input-mini"); // modify table per page dropdown
            

JS;
$this->inlineScript()->captureEnd();
?>
<?php if ($this->isGranted('project.create')) { ?>
<div id="modalDeliveryNote" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Created Delivery Note&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="deliveryNoteLoader" class="loader"></div>
        <?php echo $this->form()->openTag($form); ?>
        <p>
            Please enter the details of the delivery note:
        </p>
        <div class="control-group">
            <label class="control-label">Delivery Date</label>
            <div class="controls">
                <div class="input-append " data-date="12-02-2012" data-date-format="dd-mm-yyyy" >
                    <?php echo $this->formElement($form->get('sent'));  ?>
                    <span class="add-on" id="startDtIcon"><i class="icon-calendar"></i></span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Delivery Address</label>
            <div class="controls">
                <div id="text-toggle-button">
                    <?php echo $this->formElement($form->get('address'));  ?>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Additional Reference</label>
            <div class="controls">
                <div id="text-toggle-button">
                    <?php echo $this->formElement($form->get('reference'));  ?>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Delivered By</label>
            <div class="controls">
                <div id="text-toggle-button">
                    <?php echo $this->formElement($form->get('deliveredby'));  ?>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
        <div id="deliveryNoteMsgs"></div>
        <div class="alert alert-info no-margin-bot">
            <strong>Important 1:</strong> Delivery note details will automatically adjust system delivered values<br />
            <strong>Important 2:</strong> Subsequent to creation the PDF delivery note will be downloaded
        </div>
        <form id="documentDownloadFrm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/download" target="download-frame">
            <input type="hidden" name="documentListId" value="" />
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-deliverynote" aria-hidden="true"><i class="icon-plus"></i> Create</button>
    </div>
</div>
<?php } ?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget purple">
            <div class="widget-title">
                <h4><i class="icon-truck"></i> Delivery Notes</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <table class="table table-striped table-bordered table-advance table-hover" id="deliverynote_tbl">
                    <thead>
                        <tr>
                            <th >Id</th>
                            <th class="hidden-phone">Address</th>
                            <th >Reference</th>
                            <th class="hidden-phone">Created</th>
                            <th >Sent</th>
                            <th class="hidden-phone">Owner</th>
                            <th >&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-plus-sign-alt"></i> New Delivery Note</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
<?php if ($this->isGranted('project.write')) { ?>      
                <p>
                    Select the quantities of the products below that you would like to add to the new delivery note and click on the &quot;Add Delivery Note&quot; button to proceed.
                </p>
                <div class="btn-group pull-left">
                    <button class="btn green linkable" href="javascript:"  id="btn-add-deliverynote">
                        Add Delivery Note <i class="icon-plus"></i>
                    </button>
                </div>
                <div class=" pull-left text-error" id="errAddDeliveryNote" style="margin-left: 10px" ></div>
<?php } ?>                   
                
                <div class="space15"></div>
                <form id="deliverySystemDetails" class="form-nomargin" >
                    <div class="space15"></div>
                    <div class="alert alert-block alert-warning fade in">
                        <p>
                            Enter the quantities of the product(s) that  you wish to add to the delivery note and click on the &quot;Add Delivery Note&quot; button to proceed.
                        </p>
                    </div>
                    <table class="table table-striped table-bordered table-advance table-hover tbl-export-system" id="tbl-export-system-<?php echo $spaceId; ?>">
                        <thead>
                            <tr>
                                <th class="">Product</th>
                                <th style="width: 100px" class="row-right">Quantity</th>
                                <th style="width: 100px" class="row-right">Sent</th>
                                <th style="width: 100px" class="row-right">Unsent</th>
                                <th style="width: 100px" class="row-right">Total Qty</th>
                            </tr>
                        </thead>
                        <tbody>
                    <?php
                    if (!empty($breakdown)) {
                        foreach ($breakdown as $product) {
                            $sent = !empty($existing[$product['productId']])?$existing[$product['productId']]:0;
                            $unsent = $product['quantity']-$sent;
                            $disabled = ($unsent<=0);
                            ?>
                                    <tr>
                                        <td class=""><?php echo ucwords ($product ['model']); ?><input type="hidden" name="productId[]" value="<?php echo $product['productId']; ?>" /></td>
                                        <td class="row-right"><input value="0" <?php if ($disabled)echo 'readonly="readonly"'; ?> type="number" min="0" max="<?php echo $unsent; ?>" name="quantity[]" class="no-margin row-right" style="width:100px" /></td>
                                        <td class="row-right item-sent"><?php echo $sent; ?></td>
                                        <td class="row-right item-unsent"><?php echo $unsent; ?></td>
                                        <td class="row-right"><?php echo $product['quantity']; ?></td>
                                    </tr>
                            <?php
                        }
                            ?>
                        </tbody>  
                    </table>
                        <?php
                            }
                        ?>
                </form>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
<form method="GET" action="/client-<?php echo $project->getClient()->getClientId();?>/project-<?php echo $project->getProjectId(); ?>/document/generate" class="form-horizontal" id="formWizard" target="download-frame">
    <input name="dispatch" id="dispatch" type="hidden"  />
    <input name="documentId" id="documentId" type="hidden" value="81" />
    <input name="documentInline" id="documentInline" value="0" type="hidden" />
</form>
<iframe id="download-frame" name="download-frame" style="width:1px; height: 1px; visibility: hidden"></iframe>
