<?php 
$this->headLink()
    ->appendStylesheet('/assets/uniform/css/uniform.default.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/uniform/jquery.uniform.min.js')
    ->appendFile('/js/jquery.blockui.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/dynamic-table/project.js');

$closed = $project->getCancelled();
$job = false;


$mcd = $project->getMCD();

$prjVal = 0;
$prds = 0;
$architectural = false;
if (!empty($system)) {
    foreach ($system as $sys) {
        if (empty($sys['service'])) {
            $prds+=$sys['quantity'];
            $priceMCD = $sys['priceMCD'];
            $prjVal+=$priceMCD ;
            $tmpCpuTotal+=$sys['cost'];
            $tmpPpuTotal+=$priceMCD;
            if ($project->getIbp()) {
                $prjVal+=round($priceMCD * 0.018, 2);
            }
            if ($sys['typeId']==3) {
                $architectural = true;
            }
        } else {
            $prjVal+=$sys['price'];
        }
    }
}

?>
<?php 
$notes = $project->getNotes();
if (!empty($notes)) {
    $notesArr  = json_decode($notes, true);
    if (!empty($notesArr)) {
?>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-info relative" id="project-notes">
            <div id="noteDeleteLoader" class="loader"></div>
            <button class="close btn-add-note" >+</button>
<?php
        $cnt = 0;
        $scopeNotes = array();
        foreach ($notesArr as $idx=>$note) {
            if (is_array($note)) { // this is a scoped note
                foreach ($note as $didx=>$dnote) {
                    $cnt++;
                    $scopeNotes[] = "<strong>".ucwords($idx)." Note:</strong> {$dnote} <a data-scope=\"{$idx}\" data-index=\"{$didx}\" href=\"javascript:\" class=\"delete-note\"><i class=\"icon-remove\"></i></a>";
                }
            } else {
                $cnt++;
                echo "<div class=\"note\"><strong>Note:</strong> {$note} <a data-index=\"{$idx}\" href=\"javascript:\" class=\"delete-note\"><i class=\"icon-remove\"></i></a></div>";
            }
        }
        if (!empty($scopeNotes)) {
            echo '<div class="note">'.implode('</div><div class="note">',$scopeNotes).'</div>';
        }
?>
        </div>
    </div>
</div>
<?php
    }
}
?>
<?php
if ($project->getTest()) {
  ?>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-error">
            <strong>Important Notice:</strong> this job is in test mode and will not show up on reporting. Material generated from this project should not be presented to the client.
        </div>
    </div>
</div>
<?php
}
?>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/setup/">
                <i class="icon-gears"></i>
                <div>Configuration  </div>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/system/">
                <i class="icon-sitemap"></i>
                <div>System Overview</div>
                <span class="badge badge-success"><?php echo $prds; ?></span>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/model/">
                <i class="icon-bar-chart"></i>
                <div>Model</div>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/collaborators/">
                <i class="icon-group"></i>
                <div>Collaborators  </div>
                <span class="badge badge-important"><?php echo count($project->getCollaborators()); ?></span>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/serials/">
                <i class="icon-barcode"></i>
                <div>Serials</div>
                <span class="badge badge-important"><?php echo $serialCount; ?></span>
            </a>
            <a class="icon-btn span2 btn-add-note" href="javascript:">
                <i class="icon-calendar"></i>
                <div>Notes</div>
                <span class="badge badge-success">+</span>
            </a>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="blog span12">
        <div class="span2 <?php echo $closed?'red':($job?'green':'green'); ?>">
            <a href="javascript:;" class="blog-features date active">
                <i class=" icon-<?php echo $closed?'ban-circle':($job?'ok':'time'); ?>"></i>
                <p class="month"><?php echo $closed?'lost':($job?'job':'active'); ?></p>
            </a>
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/system/" class="blog-features comments">
                <i class=" icon-gear"></i>
                <p class="info"><?php 
                    echo $prds; 
                    ?> Products</p>
            </a>
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/serials/" class="blog-features comments">
                <i class=" icon-barcode"></i>
                <p class="info"><?php echo $serialCount; ?> Serials</p>
            </a>
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/deliverynote/" class="blog-features comments">
                <i class=" icon-truck"></i>
                <p class="info"><?php echo $dispatchNotes; ?> Delivery Notes +</p>
            </a>
        </div>
        <div class="span10">
            <h2>
                <?php echo $project->getName(); ?>
            </h2>
            <p>
                OWNER <a href="javascript:;" class="author"><?php echo strtoupper($project->getClient()->getUser()->getHandle()); ?></a> |  
                CREATED: <?php echo $project->getcreated()->format('d/m/Y H:i'); ?> | 
                REFERENCE: <?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT),'-',str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT) ?>
            </p>
            <h5>Progress<span class="pull-right"><?php echo $project->getWeighting(); ?>%</span></h5>
            <div id="slider-range-min" class="slider"></div>
            <div class="progress progress-striped progress-<?php
                if ($project->getWeighting()<10) {
                    echo 'danger';
                } elseif ($project->getWeighting()<30) {
                    echo 'warning';
                } elseif ($project->getWeighting()<50) {
                    echo 'info';
                } elseif ($project->getWeighting()<80) {
                    echo 'striped';
                } else {
                    echo 'success';
                }

            ?>">
                <div style="width: <?php echo $project->getWeighting(); ?>%;" class="bar"></div>
            </div>
            <p> Below are displayed the details of the job including information about the LED 
                systems that are contracted and a file management section in which project files can be managed. </p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th colspan="2">
                            Job Information
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 120px">
                            Job States
                        </td>
                        <td>
                            <?php 
                                $labelTypes = array(
                                    'important',
                                    'info',
                                    'success',
                                    'warning',
                                    'default',
                                );
                                $labelIdx = 0;
                                foreach ($project->getStates() as $state) {
                                    if (($state->getCompatibility() & 2)!=2) {
                                        continue;
                                    }
                                    echo '<span class="label label-'.$labelTypes[$labelIdx].' label-mini">'.ucwords($state->getName()).'</span>&nbsp;';
                                    $labelIdx++;
                                    if ($labelIdx>(count($labelTypes)-1)) {
                                        $labelIdx = 0;
                                    }
                                }
                             ?>
                        </td>
                    </tr>
                    <?php
                        $contactList = array();
                        if (!count($contacts)) {
                            $contactList[] = 'No contacts assigned to project';
                        } else {
                            foreach ($contacts as $contact) {
                                $addr = !empty($contact->getAddress())?$contact->getAddress()->assemble():'';
                                $contactList[] = '<a href="javascript:" class="contact-info" '
                                        . 'data-tel1="'.$contact->getTelephone1().'" '
                                        . 'data-tel2="'.$contact->getTelephone2().'" '
                                        . 'data-email="'.$contact->getEmail().'" '
                                        . 'data-addr="'.$addr.'" '
                                        . 'data-name="'.$contact->getName().'" '
                                        . 'data-company="'.$project->getClient()->getName().'" '
                                        . '><i class="icon-user"></i> '.$contact->getTitle()->getDisplay().' '.$contact->getForename().' '.$contact->getSurname().'</a>';
                            }
                        }
                    
                    ?>
                    <tr>
                        <td rowspan="<?php echo count($contactList); ?>">
                            Registered Contact
                        </td>
                        <td>
                            <?php 
                            echo array_shift($contactList);
                            ?>&nbsp;
                        </td>
                    </tr>
                    <?php
                        if (!empty($contactList)) {
                            echo '<tr><td>'.implode('</td></tr><tr><td>', $contactList).'</td></tr>';
                        }
                    ?>
                    <tr>
                        <td style="width: 120px">
                            Project Value
                        </td>
                        <td>&#163;
                            <?php 
                                echo number_format($figures['cost'], 2);
                             ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Project Margin
                        </td>
                        <td>
                            <?php 
                                if (($tmpPpuTotal>0) && ($tmpCpuTotal>0)) {
                                    $prjMargin = (($tmpPpuTotal - $tmpCpuTotal)/$tmpPpuTotal)*100;
                                } 
                                echo number_format($prjMargin, 2);
                             ?>%
                             <span class="badge badge-<?php echo (($prjMargin>=35)?'success':(($prjMargin>=20)?'warning':'important')); 
                             ?> pull-right"><i class="icon-<?php echo (($prjMargin>=35)?'ok':(($prjMargin>=20)?'ok':'remove')); 
                             ?>"></i> <?php echo (($prjMargin>=35)?'High':(($prjMargin>=20)?'Medium':'Low')); 
                             ?> Margin</span>
                        </td>
                    </tr>
                    <tr>
                        <td>Build Type</td>
                        <td><?php if ($architectural) {
                            echo 'Architectural <a class="pull-right" href="/client-'.$project->getClient()->getClientId().'/job-'.$project->getProjectId().'/picklist/">View Pick-List <i class="icon-shopping-cart"></i></a>';
                        } else {
                            echo 'Standard';
                        }
                            ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-cogs"></i> System Overview</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <div class="navbar navbar-static" id="navbar-example">
                    <div class="navbar-inner">
                        <div style="width: auto;" class="container">
                            <a href="#" class="brand">Options</a>
                            <ul role="navigation" class="nav">
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" role="button" id="drop2" href="#">Downloads <b class="caret"></b></a>
                                    <ul aria-labelledby="drop2" role="menu" class="dropdown-menu">
                                        <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/exportproductlist/" tabindex="-1" role="menuitem">Product List</a></li>
                                        <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/exportsystembuild/" class="btn-config-export-csv">System Setup</a></li>
                                        <?php if ($architectural) { ?>
                                        <li class="divider" role="presentation"></li>
                                        <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/picklist/?mode=1" >Picklist (Architectural)</a></li>
                                        <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/buildsheet/" >Build Sheet (Architectural)</a></li><!-- -->
                                        <?php }  ?>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" role="button" href="#" id="drop1">Architectural <b class="caret"></b></a>
                                    <ul aria-labelledby="drop1" role="menu" class="dropdown-menu">
                                <?php if ($architectural) { ?>
                                        <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/picklist/" tabindex="-1" role="menuitem">Picklist</a></li>
                                <?php } else { ?>
                                        <li role="presentation"><a>No architectural elements</a></li>
                                <?php }  ?>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-advance table-hover" id="products_tbl">
                    <thead>
                        <tr>
                            <th ><i class="icon-cog"></i> Product Name</th>
                            <th class="hidden-phone" style="width: 50px"> ID</th>
                            <th class="hidden-phone"> Product Type</th>
                            <th class="hidden-phone" style="width: 40px"> ECA</th>
                            <th class="hidden-phone" style="text-align: right"> PPU</th>
                            <th style="width: 110px; text-align: right"> Quantity</th>
                            <th style="width: 140px; text-align: right"> Price (inc MCD)</th>
                        </tr>
                    </thead>
                    <tbody>
<?php
    $totalInstallation = 0;
    $totalDelivery = 0;
    $totalAccess = 0;
    $totalOther = 0;
    $totalIbp = 0;
    
    $totalPriceMCD = 0;
    $totalQuantity = 0;
    if (!empty($system)) {
        $mcd = $project->getMCD();
        foreach ($system as $product) {
            if (!$product['service']) {
                $priceMCD = $product['priceMCD']; //round($product['price'] * (1-$mcd), 2);
                $totalPriceMCD+=$priceMCD;
                $totalQuantity+=$product['quantity'];
                if ($project->getIbp()) {
                    $totalIbp+=round($priceMCD * 0.018, 2);
                }

                echo '<tr>
                        <td><a href="/product-'.$product['productId'].'/" target="_blank">'.$product['model'].'</a></td>
                        <td>'.$product['productId'].'</td>
                        <td>'.$product['productType'].'</td>
                        <td>'.(($product['eca']==1)?'<span class="label label-success"><i class=" icon-ok"></i></span>':'<span class="label label-important"><i class=" icon-ban-circle"></i></span>').'</td>
                        <td class="row-right">'.$product['ppu'].'</td>
                        <td class="row-right">'.$product['quantity'].'</td>
                        <td class="row-right">'.number_format($priceMCD,2).'</td>
                    </tr>';
            } else {
                $price = $product['price'];
                if($product['typeId'] == 100) {
                    $totalInstallation+=$price; // type 100 is an installation product
                } elseif($product['typeId'] == 101) {
                    $totalDelivery+=$price; // type 100 is an installation product
                } elseif($product['typeId'] == 102) {
                    $totalAccess+=$price; // type 100 is an installation product
                } else {
                    $totalOther+=$price; // type 100 is an installation product
                }
                
            }
        }
        
        echo '<tr>
            <td colspan="7">&nbsp;</td>
        </tr>';
        
        echo '<tr>
                <th colspan="5">Total Product Cost</th>
                <td class="row-right">'.$totalQuantity.'</td>
                <td class="row-right">'.number_format($figures['cost_led'],2).'</td>
            </tr>';
        
        if (!empty($figures['cost_install'])) {
            echo '<tr>
                <th colspan="6">Installation Cost</th>
                <td class="row-right">'.number_format($figures['cost_install'],2).'</td>
            </tr>';

        }
        
        if (!empty($figures['cost_delivery'])) {
            echo '<tr>
                <th colspan="6">Delivery Cost</th>
                <td class="row-right">'.number_format($figures['cost_delivery'],2).'</td>
            </tr>';

        }
        
        if (!empty($figures['cost_ibp'])) {
            echo '<tr>
                <th colspan="6">Insurance Backed Premium Cost</th>
                <td class="row-right">'.number_format($figures['cost_ibp'],2).'</td>
            </tr>';

        }
        
        if (!empty($figures['cost_access'])) {
            echo '<tr>
                <th colspan="6">Access Cost</th>
                <td class="row-right">'.number_format($figures['cost_access'],2).'</td>
            </tr>';

        }
        
        if (!empty($totalOther)) {
            echo '<tr>
                <th colspan="6">Other Costs</th>
                <td class="row-right">'.number_format($totalOther,2).'</td>
            </tr>';

        }
        
        if (!empty($figures['cost_prelim'])) {
            echo '<tr>
                <th colspan="6">Prelim Fee</th>
                <td class="row-right">'.number_format($figures['cost_prelim'],2).'</td>
            </tr>';

        }
        
        if (!empty($figures['cost_overheads'])) {
            echo '<tr>
                <th colspan="6">Overheads Fee</th>
                <td class="row-right">'.number_format($figures['cost_overheads'],2).'</td>
            </tr>';

        }
        
        if (!empty($figures['cost_management'])) {
            echo '<tr>
                <th colspan="6">Management Fee</th>
                <td class="row-right">'.number_format($figures['cost_management'],2).'</td>
            </tr>';

        }
        
        if ($figures['finance_amount'] > 0) { 
            echo '<tr><td colspan="7">&nbsp;</td></tr>';
            echo 
            '<tr>
                <th colspan="6">Total Cost With Financing</th>
                <td class="row-right">'.number_format($figures['finance_amount'],2).'</td>
            </tr>
            <tr>
                <th colspan="6">Financing Period</th>
                <td class="row-right">'.number_format($figures['finance_years'],2).'</td>
            </tr>
            <tr>
                <th colspan="6">Interest Rate (Annual Flat Rate)</th>
                <td class="row-right">'.number_format($figures['finance_annual_rate'],2).'</td>
            </tr>
            <tr>
                <th colspan="6">Average Cash Benefit Over Funding Period</th>
                <td class="row-right">'.number_format($figures['finance_avg_benefit'],2).'</td>
            </tr>
            <tr>
                <th colspan="6">Average Repayments Over Funding Period</th>
                <td class="row-right">'.number_format($figures['finance_avg_repay'],2).'</td>
            </tr>
            <tr>
                <th colspan="6">Average Net Annual Benefit Over Funding Period</th>
                <td class="row-right">'.number_format($figures['finance_avg_netbenefit'],2).'</td>
            </tr>
            <tr>
                <th colspan="6">Net Cash Benefit Over Funding Period</th>
                <td class="row-right">'.number_format($figures['finance_netbenefit'],2).'</td>
            </tr>
            ';
        }
        
    }/**/
?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="6">TOTAL</th>
                            <th class="row-right">&#163;<?php echo number_format($figures['cost'],2); ?></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
<div class="row-fluid">
     <div class="span6">
         <!-- BEGIN NOTIFICATIONS PORTLET-->
         <div class="widget blue">
             <div class="widget-title">
                 <h4><i class="icon-bell"></i> Project Activity </h4>
               <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
               </span>
             </div>
             <div class="widget-body">
                 <ul class="item-list scroller padding"  style="overflow: hidden; width: auto; height: 320px;" data-always-visible="1">
                     <?php
                        if (!empty($audit)) {
                            $i=0;
                            foreach ($audit as $aItem) {
                                $tm = (time()-$aItem['created']->getTimestamp());
                                $days = floor(($tm/(60*60*24)));
                                $hours = ($tm - ($days*60*60*24))/(60*60);
                                $when= (($tm/60)<2)
                                        ?'Just now'
                                        :(
                                            (($tm/60)<60)
                                            ?ceil($tm/60).' mins ago'
                                            :(
                                                ($days<1)
                                                ?floor($hours).' hour'.(($hours>=2)?'s':'').' ago'
                                                :$days.' day'.(($days>=2)?'s':'').' '.(
                                                    ($hours>0)
                                                    ?floor($hours).' hour'.(($hours>=2)?'s':'').' '
                                                    :''
                                                ).'ago'    
                                            )
                                        );
                                
                                $tooltip_data = '';
                                $tooltip = '';
                                $url = '';
                                
                                $aData = json_decode($aItem['data'], true);
                                
                                if (!empty($aItem['dName'])) {
                                    $tooltip_data.=$aItem['dName'];
                                    if (!empty($aItem['projectId'])) {
                                        $url = '/client-'.$aItem['clientId'].'/project-'.$aItem['projectId'].'/document/index/';
                                    }
                                } elseif (!empty($aItem['model'])) {
                                    $tooltip_data.=trim($aItem['model']);
                                    $url = '/client-'.$aItem['clientId'].'/project-'.$aItem['projectId'].'/space-'.$aItem['spaceId'].'/';
                                } elseif (!empty($aItem['sName'])) {
                                    $tooltip_data.=$aItem['sName'];
                                    $url = '/client-'.$aItem['clientId'].'/project-'.$aItem['projectId'].'/space-'.$aItem['spaceId'].'/';
                                } 
                                
                                if (!empty($tooltip_data)) {
                                    $tooltip = 'data-trigger="hover" data-placement="right" data-original-title="'.$tooltip_data.'"';
                                }
                                
                                
                                
                                //break;
                                echo '<li>
                                    <span '.$tooltip.' class="audit '.(empty($tooltip)?'':'tooltips ').'label label-'.(empty($aItem['box'])?'success':$aItem['box']).'" '
                                        . (!empty($url)?'data-url="'.$url.'" data-link="true"':'')
                                    . '><i '
                                        . 'class="icon-'.(empty($aItem['icon'])?'bell':$aItem['icon']).'"></i></span>
                                    <span class="link">'.
                                        $aItem['atName'].
                                    '</span>
                                    <div class="pull-right">
                                        <span class="small italic ">'.$when.'</span>
                                    </div>
                                </li>';
                            } 
                        } else {
                             echo '<li>
                                    <span class="label label-default"><i class="icon-bell"></i></span>
                                    <span class="link">No Activity Information Found</span>
                                    <div class="pull-right">
                                        <span class="small italic ">&nbsp;</span>
                                    </div>
                                </li>';
                        }
                    ?>  
                 </ul>
                 <div class="space10"></div>
                 <a href="#" class="pull-right">View detailed notifications</a>
                 <div class="clearfix no-top-space no-bottom-space"></div>
             </div>
         </div>
         <!-- END NOTIFICATIONS PORTLET-->
     </div>
     <div class="span6">
         <!-- BEGIN CHAT PORTLET-->
         <?php echo $this->partial('partial/panels/activity.phtml'); ?>
         <!-- END CHAT PORTLET-->
     </div>
 </div>
<?php echo $this->partial('partial/project/notes.phtml'); ?>
<?php echo $this->partial('partial/contact/dialog.phtml'); ?>