<?php

$client = $project->getClient();
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/forms/trial/serials.js');


$this->inlineScript()->captureStart();

echo <<<JS

    $(function(){
        var serialTable = $('#serials_tbl').dataTable({
            sDom: "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
            sPaginationType: "bootstrap",
            oLanguage: {
                sLengthMenu: "_MENU_ records per page",
                oPaginate: {
                    sPrevious: "Prev",
                    sNext: "Next"
                }
            },
            bProcessing: true,
            bServerSide: true,
            iDisplayLength:25,
            aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
            aoColumns: [
                null,
                null,
                null,
                { 'bSortable': false, "sClass": "hidden-phone" },
                { "sClass": "hidden-phone" },
            ],
            sAjaxSource: "/client-{$client->getClientId()}/job-{$project->getProjectId()}/seriallist/"
        });    

        jQuery('#serials_tbl_wrapper .dataTables_filter input').addClass("input-medium"); // modify table search input
        jQuery('#serials_tbl_wrapper .dataTables_length select').addClass("input-mini"); // modify table per page dropdown
        
        $('#modalSerialAdd').on('hidden.bs.modal', function (e) {
            serialTable.fnDraw();
        });
    });
    
            
            
JS;
$this->inlineScript()->captureEnd();
?>
<div id="modalSerialAdd" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Add Serial To Project&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="serialAddLoader" class="loader"></div>
        <p>
            If you have the product and space information for the product then you can (optionally) select the product/space from the below lists:
        </p>
        <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formElement($form->get('projectId'));  ?>
            <div class="control-group">
                <label class="control-label">Product</label>
                <div class="controls">
                    <?php echo $this->formElement($form->get('products'));  ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">System</label>
                <div class="controls">
                    <select id="sel-system" class="span10" name="systemId">
                        <option value="" >Select Placement (optional)</option>
                    </select>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Range</label>
                <div class="controls">
                    <?php echo $this->formElement($form->get('range'));  ?>
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label">First Serial Number</label>
                <div class="controls">
                     <?php echo $this->formElement($form->get('serialStart'));  ?>
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label">Last Serial Number</label>
                <div class="controls">
                    <label id="serialEnd">-</label>
                </div>
            </div> 
        <?php echo $this->form()->closeTag($form); ?>
        <div id="serialMsgs"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-add-serials" aria-hidden="true"><i class="icon-plus-sign"></i> Add Serial Range</button>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget purple">
            <div class="widget-title">
                <h4><i class="icon-barcode"></i> Registered Serials</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
<?php if ($this->isGranted('project.write')) { ?>                    
                    <div class="btn-group pull-left">
                        <button class="btn green linkable" href="javascript:"  id="btn-add-serial-modal">
                            Add Serial <i class="icon-plus"></i>
                        </button>
                    </div>
<?php } ?>                    
                <div class="btn-group pull-right">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:">Export to Excel</a></li>
                        </ul>
                </div>
                <div class="space15"></div>
                <table class="table table-striped table-bordered table-advance table-hover" id="serials_tbl">
                    <thead>
                        <tr>
                            <th ><i class="icon-barcode"></i> Serial Number</th>
                            <th > Product Type</th>
                            <th > Space</th>
                            <th class="hidden-phone" > Status</th>
                            <th class="hidden-phone" style="width: 160px"> Registration Date</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>