<?php

$this->inlineScript()
    ->appendFile('/js/forms/job/system.js')
    ;


$this->headStyle()->captureStart() 
?>
    .tbl-export-building label {
        margin:0; 
        padding:0;
    }
<?php 
$this->headStyle()->captureEnd();

echo $this->partial('partial/system/csvpdfdownload.phtml');

?>
<?php if (!empty($projisExportEnabled)) { ?>        
<div id="modalExportToProjis" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Export to Projis</h3>
    </div>
    <div class="modal-body">
        <div id="exportToProjisLoader" class="loader"></div>
        <p>
            Are you sure that you would like to export this job to Projis?<br /><br />
            Warning: this will create a supply-only project in Projis with aggregated system data in the root space.
            <form id="frmExportToProjis" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/export/projis/"></form>
        </p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-export-to-projis" aria-hidden="true"><i class="icon-ok"></i> Confirm</button>
    </div>
</div> 
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav metro-fix-view">
        <div class="metro-nav-block nav-block-yellow">
            <a href="#modalExportToProjis" data-toggle="modal" href="javascript:" data-original-title="" id="btn-export-to-projis">
                <div class="text-center">
                    <i class="icon-chevron-sign-right"></i>
                </div>
                <div class="status">Export to Projis</div>
            </a>
        </div>
    </div>
</div>
<?php } ?>  
<div class="row-fluid">
    <div class="span12" id="right_column">
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-cog"></i> System Setup</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="systemEditLoader" class="loader"></div>
                <div>
                    <div class="clearfix">
                        <div class="btn-group pull-left">
                            <button id="btn-select-all" class="btn green" style="margin-right: 4px">
                                Show All Items <i class="icon-check"></i>
                            </button>
                            <button id="btn-deselect-all" class="btn green" style="margin-right: 4px">
                                Hide All Items <i class="icon-check-empty"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:" class="btn-config-export-csv">Export Full System to CSV</a></li>
                                <li><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/job-<?php echo $project->getProjectId(); ?>/export/">Export Wizard</a></li>
                            </ul><!-- -->
                        </div>
                    </div>
                    <div class="space5"></div>
                    <form id="exportSystemDetails" class="form-nomargin" >
                    <?php
                    if (!empty($breakdown)) {
                        foreach ($breakdown as $buildingId => $building) {
                    ?>
                    <div class="space15"></div>
                    <table class="table table-striped table-bordered table-advance tbl-export-building" id="tbl-export-building-<?php echo $buildingId; ?>">
                        <thead>
                            <tr>
                                <th>
                                    <label><i class="icon-chevron-down chbx-building" data-buildingId="<?php echo $buildingId; ?>"></i> Building: <?php echo ($buildingId==0)?'Global':ucwords($building ['name']); ?></label>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                        <?php 
                            foreach ($building ['spaces'] as $spaceId => $space) {
                                $root = !empty($space['root']);
                                
                        ?>
                                    <div class="div-export-space"> 
                                        <div class="alert alert-success no-margin-bot">
                                            <label><i class="icon-chevron-down chbx-space" data-spaceId="<?php echo $spaceId; ?>"></i> Space: <?php echo ucwords ($space ['name']); ?></label>
                                        </div>
                                        <table class="table table-striped table-bordered table-advance table-hover tbl-export-system" id="tbl-export-system-<?php echo $spaceId; ?>">
                                            <thead>
                                                <tr>
                                                    <th style="width: 200px" class="">Product</th>
                                                    <th style="width: 60px" class="">Qty</th>
                                                    <th style="width: 60px" class="">Hrs</th>
                                                    <th class="">Legacy</th>
                                                    <th class="">Additional</th>
                                                    <th style="width: 100px" class="row-right">Total Cost</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php

                                    foreach ( $space['products'] as $systemId => $system) {
                                        $disabled = (!$root && ($system[2]==100));
                                        
                                        $additional = '';
                                        if ($system[2]==3) {
                                            if (!empty($system[16])) {
                                                
                                                $attr = json_decode($system[16], true);
                                                $config = '';
                                                foreach ($attr['dConf'] as $icnf) {
                                                    foreach ($icnf as $cnf=>$qtty) {
                                                        for ($k=0; $k<$qtty; $k++) {
                                                            $config.='['.$cnf.']';
                                                        }
                                                    }
                                                    $config.='<br>';
                                                }
                                                $additional.='Specified: '.$attr['sLen'].'mm, Achievable: '.$attr['dLen'].'mm, Units: '.(empty($attr['dUnits'])?1:$attr['dUnits']).' '
                                                        . '<i class="icon-cog popovers" data-trigger="hover" data-html="true" data-placement="top" data-content="'.$config.'" data-original-title="'.ucwords ($system [4]).'"></i><div style="display: none">'.$config.'</div>';
                                            }
                                            
                                        }
                                        
                                        ?>
                                                <tr>
                                                    <td class=""><?php echo ucwords ($system [4]); ?></td>
                                                    <td class=""><?php echo $system [5]; ?></td>
                                                    <td class=""><?php echo $system [6]; ?></td>
                                                    <td class=""><?php echo empty($system [8])?'-':ucwords($system [8]); ?></td>
                                                    <td><?php echo $additional; ?></td>
                                                    <td class="row-right"><?php echo number_format($system [1],2); ?></td>
                                                </tr>
                                        <?php
                                    }
                                        ?>
                                            </tbody>  
                                        </table>
                                        <br class="clearfix" />
                                    </div>
                        <?php
                            }
                        ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                            <?php
                        }
                    }

                    ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>