<?php
//$this->headLink()->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/signalr/jquery.signalr-1.1.2.min.js')
    ->appendFile('https://testing.wattzo.com/api/realtime/hubs')
;/**/

$this->inlineScript()->captureStart();
echo <<<JS
var Sliders = function () {
    var rate = 5;
    var hubId = "01-001-1CE70B";
    var token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3dhdHR6by5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0LyIsImF1ZCI6Imh0dHBzOi8vdGVzdGluZy53YXR0em8uY29tLyIsIm5iZiI6MTQxNTg5MTMyMiwiZXhwIjoyNTM0MDIzMDA3OTksImVtYWlsIjoiam9ubnkucC5jb29rQDhwb2ludDNsZWQuY28udWsiLCJ1bmlxdWVfbmFtZSI6Ikpvbm55IENvb2siLCJuYW1laWQiOiIxZGNiYzE4YjczNTU0OWE1ODdhMjRjNzNiZjYwNjFkMSIsImlkZW50aXR5cHJvdmlkZXIiOiJXYXR0em8ifQ.RKkiJ-xIdrUbbN382iIaXn8BiK14x3XA9XDAYk0i3lo';
    var serviceUri = 'https://testing.wattzo.com/api/realtime';

    var devices = {
        '01-710-00FA32':{color:'red', status: 'pending'},
        '01-710-7EE508':{color:'green', status: 'pending'},
        '01-710-1704FF':{color:'blue', status: 'pending'},
        '01-710-4F9137':{color:'white', status: 'pending'}
    };

    var tblDevices = $('#tbl-devices tbody');
    tblDevices.empty();
    for (var serial in devices) {
        tblDevices.append($('<tr>')
            .attr('data-did',serial)
            .append(
            $('<td>').text(serial),
            $('<td>').text(devices[serial].color),
            $('<td>').text(devices[serial].status)
        ));
    }

    function refreshDeviceStatus() {
        for (var serial in devices) {
            tblDevices.find('tr[data-did="'+serial+'"] td:nth-child(3)').text(devices[serial].status);
        }
    }

// vertical slider
    $("#slider-vertical-red").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-red-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-00FA32', ui.value);
        }
    });

    $("#slider-vertical-green").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-green-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-7EE508', ui.value);
        }
    });

    $("#slider-vertical-blue").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-blue-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-1704FF', ui.value);
        }
    });

    $("#slider-vertical-white").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-white-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-4F9137', ui.value);
        }
    });/**/

    $("#slider-vertical-rate").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: rate,
        slide: function (event, ui) {
            $("#slider-vertical-rate-amount").text(ui.value);
        },
        change: function (event, ui) {
            rate =  ui.value;
        }
    });

    $("#slider-vertical-red-amount").text($("#slider-vertical-red").slider("value"));
    $("#slider-vertical-green-amount").text($("#slider-vertical-green").slider("value"));
    $("#slider-vertical-blue-amount").text($("#slider-vertical-blue").slider("value"));
    $("#slider-vertical-white-amount").text($("#slider-vertical-white").slider("value"));
    $("#slider-vertical-rate-amount").text($("#slider-vertical-rate").slider("value"));

    function channelChange(deviceId, value) {    
        CallRestAPI(
            'PUT',
            'hubs/'+hubId+'/devices/'+deviceId+'/level',
            'level='+value+'&rate='+rate,
            token
        );
        //console.log('Device: '+deviceId+' = '+value);
    }


    function CallRestAPI(method, endPoint, param, token)
    {
        var weblink = "https://testing.wattzo.com/api/"+endPoint;
        //console.log(weblink); return;
        
        $.ajax(
        {
            url : weblink,
            type : method,
            data: param,
            dataType: 'json',
            beforeSend: function (request)
            {
                if ((token!=undefined) && (token!=null)) {
                    request.setRequestHeader("Authorization", "Bearer "+token);
                }
            },
            crossDomain: true,
            success : function(result, textStatus, request)
            {
                //process the result
                //console.log(result);
                //console.log(textStatus);
                //console.log(request.status);
                /*for (i in result.data) {
                    //console.log(result.data[i].id);
                }/**/
            },
            error : function(jqXHR, textStatus, errorThrown) {
                alert('Error: '+jqXHR.status);
                alert('ErrorThrown: '+errorThrown)
            }
        });
    }

    $.signalR.hub.url = serviceUri;
    $.connection.hub.qs = "id=" + hubId;
    $.ajaxSetup({ beforeSend: function (request)
    {
        request.setRequestHeader("Authorization", "Bearer "+token);
    }});

    $.connection.realtime.client.onUsageReceived = function (usage) {
        //console.info("Usage received for hub.", usage.devices);
        var changed = false;
        for(var i in usage.devices){
            //console.info("Usage received for hub.", usage.devices[i]);
            if (devices[usage.devices[i].id]==undefined) {
                continue; 
            }
            
            if (devices[usage.devices[i].id].status == usage.devices[i].connectionStatus) {
                continue;
            }
            devices[usage.devices[i].id].status = usage.devices[i].connectionStatus;
            changed = true;
        }/**/
        
        if(changed) {
            refreshDeviceStatus();
        } 
    };  

    $.connection.hub
    .start({ transport: 'longPolling' })
    //.start()
    .done(function() {
            //console.info("Subscribed to realtime feed.", serialNumber);
    })
    .fail(function(ex) {
            //console.error("Error occurred while subscribing to realtime feed.", ex);
    });/**/

    
}();
JS;
$this->inlineScript()->captureEnd();

?>

<div class="row-fluid">
    <div class="span6">
      <!-- BEGIN SLIDER PORTLET-->
      <div class="widget blue">
            <div class="widget-title">
               <h4><i class="icon-bar-chart"></i> Level Settings </h4>
               <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body">
                <table class="table sliders">
                    <tbody>

                    <tr>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                <span class="text-error">Red:</span> <span  class="slider-info" id="slider-vertical-red-amount"></span>
                            </div>
                            <div id="slider-vertical-red" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                <span class="text-success">Green:</span> <span  class="slider-info" id="slider-vertical-green-amount"></span>
                            </div>
                            <div id="slider-vertical-green" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                               <span class="text-info">Blue:</span> <span  class="slider-info" id="slider-vertical-blue-amount"></span>
                            </div>
                            <div id="slider-vertical-blue" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                White: <span  class="slider-info" id="slider-vertical-white-amount"></span>
                            </div>
                            <div id="slider-vertical-white" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                Rate: <span  class="slider-info" id="slider-vertical-rate-amount"></span>
                            </div>
                            <div id="slider-vertical-rate" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td></td>
                    </tr>

                    </tbody>
                </table>
                
            </div>
      </div>
      <!-- END SLIDER PORTLET-->
    </div>
    <div class="span6">
      <!-- BEGIN SLIDER PORTLET-->
      <div class="widget">
            <div class="widget-title">
               <h4><i class="icon-bar-chart"></i> Device Status </h4>
               <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body">
                <table class="table table-bordered table-striped" id="tbl-devices">
                    <thead>
                        <tr>
                            <th>Device</th>
                            <th>Colour</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
                
            </div>
      </div>
      <!-- END SLIDER PORTLET-->
    </div>
</div>

