<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-blue">
            <a data-original-title="" href="/playground/routemapping/">
                <i class="icon-road"></i>
                <div class="info">Maps</div>
                <div class="status">Route Mapping</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-purple">
            <a data-original-title="" href="/playground/colourdimming/">
                <i class="icon-lightbulb"></i>
                <div class="info">Dimming</div>
                <div class="status">DALI colour dimming</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-green">
            <a data-original-title="" href="/playground/hmrc/">
                <i class="icon-mobile-phone"></i>
                <div class="info">HM Prisons</div>
                <div class="status">Activation Demo</div>
            </a>
        </div>
    </div>
</div>