<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN PROGRESS PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-tasks"></i> Map</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                This service is currently unavailable
            </div>
        </div>
    </div>
</div>