<?php
    $this->headLink()
            ->appendStylesheet('/assets/bootstrap-datepicker/css/datepicker.css')
            ->appendStylesheet('/assets/bootstrap-timepicker/compiled/timepicker.css');
    $this->inlineScript()
            ->appendFile('/assets/bootstrap-datepicker/js/bootstrap-datepicker.js')
            ->appendFile('/assets/bootstrap-timepicker/js/bootstrap-timepicker.js');
    
    
    $this->inlineScript()->appendFile('/js/forms/activity/tools.js');
    
    $projectMode = false;
    if ($formActivity->has('projectId')) { 
        $projectMode = ($formActivity->get('projectId')->getAttribute('type')=='hidden');
    }
        
    $clientMode = false;
    if ($formActivity->has('clientId')) { 
        $clientMode = ($formActivity->get('clientId')->getAttribute('type')=='hidden');
    }
        
?>
<div class="widget red">
    <div class="widget-title">
        <h4><i class="icon-comments-alt"></i> Recent Account Activity</h4>
               <span class="tools">
               <a href="javascript:;" class="icon-info-sign"></a>
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
    </div>
    <div class="widget-body">
        <div class="timeline-messages scroller" style="overflow: hidden; width: auto; height: 180px" data-always-visible="1" id="activity-log">
            <!-- Comment -->
           <?php
               if (!empty($activities)) {
                   $i=0;
                   foreach ($activities as $activity) {
                       echo '<div class="msg-time-chat"> '
                           . '<a class="message-img" href="#">'
                           . '<img alt="" src="/resources/user/avatar/'.(empty($activity['picture'])?'default':$activity['picture']).'.jpg" class="avatar">'
                           . '</a>'
                           . '<div class="message-body msg-'.(($activity['userId']!=$user->getUserId())?'in':'out').'">'
                           . '<span class="arrow"></span>'
                           . '<div class="text">'
                           . '<p class="attribution"><a href="#">'.ucwords(trim($activity['forename'].' '.$activity['surname'])).'</a> at '.$activity['startDt']->format('g:ia, jS F Y').'<br />Activity: '
                           . $activity['atName']
                           . (!empty($activity['projectId'])
                               ?' for project'.($projectMode?'':' <a href="/client-'.$activity['clientId'].'/project-'.$activity['projectId'].'/">'.$activity['pName'].'</a>')
                               :(!empty($activity['clientId'])
                                   ?' for client'.($clientMode?'':' <a href="/client-'.$activity['clientId'].'/">'.$activity['cName'].'</a>')
                                   :''
                               )
                               )
                           . '</p>'
                           . '<p>'.$activity['note'].'</p>'
                           . '</div>'
                           . '</div>'
                           . '</div>'
                           ;

                   } 
               } else {
                    echo '<div class="msg-time-chat">
                <a class="message-img" href="#"></a>
                <div class="message-body msg-in">
                    <span class="arrow"></span>
                    <div class="text">
                        <p>No activities added to project</p>
                    </div>
                </div>
            </div>';
               }
           ?>                      
       </div>
       <div class="chat-form relative">
            <div id="quickSendLoader" class="loader"></div>
            <?php echo $this->form()->openTag($formActivity); ?>
                <div id="div-advanced-activity" style="display: none">
                    <?php
                    if ($formActivity->has('clientId')) { 
                        if ($formActivity->get('clientId')->getAttribute('type')=='hidden') { 
                            echo $this->formElement($formActivity->get('clientId')); 
                        } else {
                        ?>
                    <div class="input-cont">
                        <div class="controls span10">
                            <?php echo $this->formElement($formActivity->get('clientId'));  ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                        <?php
                        }
                    }
                    ?>
                    <?php
                    if ($formActivity->has('projectId')) { 
                        if ($formActivity->get('projectId')->getAttribute('type')=='hidden') { 
                            echo $this->formElement($formActivity->get('projectId')); 
                        } else {
                        ?>
                    <div class="input-cont">
                        <div class="controls span10">
                            <?php echo $this->formElement($formActivity->get('projectId'));  ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                        <?php
                        }
                    }
                    ?>
                    <div class="input-cont">
                        <div class="controls span6">
                            <?php echo $this->formElement($formActivity->get('activityTypeId'));  ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="input-cont">
                        <div class="controls span6">
                            <div class="input-append">
                                <?php echo $this->formElement($formActivity->get('duration'));  ?>
                                <span class="add-on label label-info">mins</span>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="input-cont">
                        <div class="controls span6">
                            <div class="input-append " id="dpYears" data-date="12-02-2012" data-date-format="dd-mm-yyyy" >
                                <?php echo $this->formElement($formActivity->get('startDt'));  ?>
                                <span class="add-on" id="startDtIcon"><i class="icon-calendar"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="input-cont">
                        <div class="controls span6">
                            <div class="input-append bootstrap-timepicker">
                                <?php echo $this->formElement($formActivity->get('startTm'));  ?>
                                <span class="add-on"><i class="icon-time"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="input-cont">
                    <?php echo $this->formElement($formActivity->get('note'));  ?>
                </div>
                <div class="btn-cont">
                    <a href="javascript:;" class="btn btn-primary" id="btn-activityQS">Send</a>
                </div>
                <div class="space10"></div>
                <a href="javascript:" id="btn-advanced-activity">Advanced Activity <i class="icon-chevron-sign-right"></i></a>
<?php
    if($projectMode) {
        echo '<a href="/client-'.$project->getClient()->getClientId().'/project-'.$project->getProjectId().'/activity/" class="pull-right">View detailed project activity log</a>';
    } elseif($clientMode) {
        echo '<a href="/client-'.$client->getClientId().'/activity/" class="pull-right">View detailed client activity log</a>';
    } else {
        echo '<span class="pull-right">Quick Send is a &quot;General&quot; Activity of 5 mins</span>';
    }
?>
                
                <!--<!-- -->
                <div class="clearfix"></div>
            <?php echo $this->form()->closeTag($formActivity); ?>
        </div>
    </div>
</div>