<?php
$selectable = $hasgoogle?($eventaware?'true':'false'):'false';

// additional css
$this->headLink()
    //->appendStylesheet('/assets/fullcalendar/fullcalendar2/fullcalendar.min.css')
    ->appendStylesheet('/assets/fullcalendar/fullcalendar2/fullcalendar.min.css')
       ;

//additional scripts
$this->inlineScript()
    ->appendFile('/assets/fullcalendar/fullcalendar2/lib/moment.min.js')
    //->appendFile('/assets/fullcalendar/fullcalendar2/fullcalendar.min.js')
    ->appendFile('/assets/fullcalendar/fullcalendar2/fullcalendar.js')

//page specific scripts
;
$defaultView = !empty($this->monthview)?'month':'agendaWeek';
$calendarUserStr = !empty($calendarUser)?'?userId='.$calendarUser->getUserId():'';
$events = !$hasgoogle?'':', events: {
                url: \'/calendar/eventlist/'.$calendarUserStr.'\',
				error: function() {
					$(\'#script-warning\').show();
				}
        }/**/';
    
$this->inlineScript()->captureStart();
echo <<<JS
    var Script = function () {

//    calender

    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();

    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        defaultView: '{$defaultView}',
        selectable: {$selectable},
        selectHelper: true,
        select: function(start, end) {
            var allDayEvent = (((end.format('X') - start.format('X'))%86400)==0);
            var sameDayEvent = ((end.format('X') - start.format('X')) == 86400);
            if (allDayEvent) {
                $('input[name=calStartDt]').val(start.format('DD/MM/YYYY'));
                $('input[name=calStartTm]').val('');
                
                $('input[name=calEndDt]').val(sameDayEvent?start.format('DD/MM/YYYY'):moment(end.format('X'), 'X').format('DD/MM/YYYY'));
                $('input[name=calEndTm]').val('');
                
                $('input[name=calDt]').val(start.format('dddd MMMM D YYYY')+(sameDayEvent?'':' - '+moment(end.format('X')-86400, 'X').format('dddd MMMM D YYYY')));
            } else {
                $('input[name=calStartDt]').val(start.format('DD/MM/YYYY'));
                $('input[name=calStartTm]').val(start.format('HH:mm'));
                $('input[name=calEndDt]').val(end.format('DD/MM/YYYY'));
                $('input[name=calEndTm]').val(end.format('HH:mm'));
                $('input[name=calDt]').val(start.format('dddd MMMM YYYY HH:mm')+' - '+end.format('HH:mm'));
            }
            
            $('#myModalNewEvent').modal('show');
        },
        editable: false,
        eventLimit: true, // allow "more" link when too many events
        loading: function(bool) {
            if (bool) {
                $('#loading').fadeIn();
            } else {
                $('#loading').fadeOut();
            }
        }
        {$events}
    });


    
    $(document).on('click','.fc-day-number-sel', function(e) {
        e.preventDefault();
        e.stopPropagation();
        $('#calendar').fullCalendar('gotoDate', $(this).parent().attr('data-date'));
        $('#calendar').fullCalendar('changeView', 'agendaDay');
        return false;
    });



}();

JS;
$this->inlineScript()->captureEnd();
?>
<!-- BEGIN CALENDAR PORTLET-->
<div class="widget yellow">
    <div class="widget-title">
        <h4><i class="icon-calendar"></i> Calendar</h4>
        <span class="tools">
            <a href="javascript:;" class="icon-chevron-down"></a>
            <a href="javascript:;" class="icon-remove"></a>
        </span>
    </div>
    <div class="widget-body relative">
        <div class="loader" id="loading"></div>
        <div id="calendar" class="has-toolbar"></div>
    </div>
</div>
<!-- END CALENDAR PORTLET-->
<?php if ($hasgoogle && $eventaware) { 
    $this->headLink()
            ->appendStylesheet('/assets/bootstrap-datepicker/css/datepicker.css')
            ->appendStylesheet('/assets/bootstrap-timepicker/compiled/timepicker.css');
    $this->inlineScript()
            ->appendFile('/assets/bootstrap-datepicker/js/bootstrap-datepicker.js')
            ->appendFile('/assets/bootstrap-timepicker/js/bootstrap-timepicker.js');
    
$this->inlineScript()->captureStart();
echo <<<JS
var ScriptActivityTools = function () {
    $('#btn-addadvanced').on('click', function(e) {
        e.preventDefault();
        document.location = '/calendar/advancedevent/?'+$('#{$formCalendarEvent->getName()}').serialize();
        return false;
    });

    $('#btn-addevent').on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();

        try {
            resetFormErrors('{$formCalendarEvent->getName()}');
            var url = $('#{$formCalendarEvent->getName()}').attr('action');
            var params = 'ts='+Math.round(new Date().getTime()/1000)+'&'+$('#{$formCalendarEvent->getName()}').serialize()+'&nogrowl=1';

            $('#calendarEventLoader').fadeIn(function(){
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: params, // Just send the Base64 content in POST body
                    processData: false, // No need to process
                    timeout: 60000, // 1 min timeout
                    dataType: 'text', // Pure Base64 char data
                    beforeSend: function onBeforeSend(xhr, settings) {},
                    error: function onError(XMLHttpRequest, textStatus, errorThrown) {},
                    success: function onUploadComplete(response) {
                        //console.log(response); //return;
                        try{
                            var obj=jQuery.parseJSON(response);
                            var k = 0;
                            // an error has been detected
                            if (obj.err == true) {
                                if (obj.info != undefined) {
                                    for(var i in obj.info){
                                        addFormError(i, obj.info[i]);
                                    }
                                }
                            } else{ // no errors
                                $('#myModalNewEvent').modal('hide');
                                growl('Success!', 'The event has been added successfully.', {time: 3000});
                                eventData = {
                                    title: obj.info.title,
                                    start: obj.info.start,
                                    end: obj.info.end,
                                    url: '/calendar/advancededit/?eid='+obj.info.id,
                                    textColor: '#468847',
                                    backgroundColor: '#dff0d8',
                                    borderColor: '#d6e9c6'
                                };
                                $('#calendar').fullCalendar('renderEvent', eventData, true); // stick? = true

                            }
                        }
                        catch(error){
                            $('#errors').html($('#errors').html()+error+'<br />');
                        }
                    },
                    complete: function(jqXHR, textStatus){
                        $('#calendarEventLoader').fadeOut(function(){});
                    }
                });
            });

        } catch (ex) {

        }/**/
       
        return false;
    });
    
}();    
JS;
$this->inlineScript()->captureEnd();
?>

<div id="myModalNewEvent" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel2">Add New Event</h3>
    </div>
    <div class="modal-body relative">
        <div id="calendarEventLoader" class="loader"></div>
        <!-- BEGIN FORM-->
        <?php echo $this->form()->openTag($formCalendarEvent); ?>
            <input type="hidden" name="calStartDt" />
            <input type="hidden" name="calStartTm" />
            <input type="hidden" name="calEndDt" />
            <input type="hidden" name="calEndTm" />
            <div class="control-group">
                <input type="text" name="calDt" class="span12" value="" readonly="true" />
            </div>
            <div class="control-group">
                <label class="control-label">Event Summary</label>
                <div class="controls">
                    <?php echo $this->formElement($formCalendarEvent->get('title'));  ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag($formCalendarEvent); ?>
        <!-- END FORM-->
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" id="btn-addevent" aria-hidden="true">Add Event <i class="icon-plus"></i></button>
        <button class="btn btn-primary" id="btn-addadvanced" aria-hidden="true">Advanced <i class="icon-forward"></i></button>
    </div>
</div>
<?php } ?>
