<?php
    $client = $project->getClient();

    
?><html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>8point3 LED document</title>
        
        <?php
            echo $this->partial('partial/project/docs/css.phtml'); 
        ?>
        
    </head>
    <body>
        <?php 
            if (!empty($footer['pages'])) {
                echo $this->partial('partial/project/docs/pages.phtml'); 
            }
            
        ?>
        <div>
            <style>
                #orderconfirmation_logo {
                    width: 240px;
                    position: absolute;
                    right: 0;
                    top: 0;
                }

                #orderconfirmation_title {
                    left: 0;
                    top: 0;
                    font-size: 9pt;
                    line-height: 10pt;
                    text-align: left;
                    min-height: 50px;
                }
                
                #orderconfirmation_details { 
                    margin-bottom: 20px;
                }
                
                .tbl-orderconfirmation-info,
                .tbl-orderconfirmation-items {
                    font-size: 9pt!important;
                    border-spacing: 0;
                }
                
                .tbl-orderconfirmation-info td {
                    text-align: left;
                    padding:0;
                    margin:0;
                }

                .tbl-orderconfirmation-info th {
                    text-align: left;
                    margin:0;
                    padding:0;
                    padding-right: 4px;
                }

                .tbl-orderconfirmation-items {
                    width: 100%;
                }
                
                .tbl-orderconfirmation-items thead th {
                    text-align: left;
                    padding: 4px 0;
                }

                .tbl-orderconfirmation-items tbody td {
                    padding: 4px 0;
                }

                .tbl-orderconfirmation-items thead {
                    border-top: 1px #111 solid;
                    border-bottom: 1px #111 solid;
                }
                
                #orderconfirmationfoot {
                    font-size: 9pt!important;
                    line-height: 10pt;
                    border-top: 1px #111 solid;
                    width: 100%;
                    padding: 10px 0;
                }
                
                #deliverynotes  {
                    font-size: 8pt!important;
                }

                

            </style>
            <img id="orderconfirmation_logo" src="<?php echo $resourcesUri; ?>img/logo-8p3-1.png" />
            <div id="orderconfirmation_title">
                <h2>ORDER CONFIRMATION</h2>
            </div>
            <div id="orderconfirmation_details">
                <table class="tbl-orderconfirmation-info">
                    <tbody>
                        <tr>
                            <th>Client Name</th>
                            <th>:</th>
                            <td><?php echo $project->getClient()->getName(); ?></td>
                        </tr>
                        <tr>
                            <th>Project Name</th>
                            <th>:</th>
                            <td><?php echo $project->getName(); ?></td>
                        </tr>
                        <tr>
                            <th>Reference</th>
                            <th>:</th>
                            <td><?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT).'-'.str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT); ?></td>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <th>:</th>
                            <td><?php echo date('l jS F Y'); ?></td>
                        </tr>
                        <tr>
                            <th>Client Contact</th>
                            <th>:</th>
                            <td><?php echo $contact->getName(); 
                                if ($contact->getAddress() instanceof Contact\Entity\Address) {
                                    echo ', ', $contact->getAddress()->assemble(', ');
                                }
                            ?></td>
                        </tr>
                        <tr>
                            <th>Delivery Address</th>
                            <th>:</th>
                            <td><?php echo $dAddress->assemble(', '); ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <table class="tbl-orderconfirmation-items">
                <thead>
                    <tr>
                        <th style="width: 180px">Product</th>
                        <th>Description</th>
                        <th style="width: 60px; text-align: right">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        if (!empty($billitems)) {
                            foreach ($billitems as $item) {
                                if (!$item['service']) { // echo products
                                    echo '<tr>'
                                        . '<td class="left">'.$item['model'].'</td>'
                                        . '<td class="left">'.$item['description'].'</td>'
                                        . '<td class="right">'.$item['quantity'].'</td></tr>';
                                }
                                
                            }
                        }
                    ?>
                </tbody>
            </table>
            <div id="orderconfirmationfoot">
                <p>We can confirm that this order has been entered into our manufacturing process and estimated delivery dates will be
confirmed in due course. For more information please contact our Project Delivery Team on 01322 270 400.</p>
            </div>
<?php
/*$notes = $project->getNotes();
if (!empty($notes)) {
    $notesArr  = json_decode($notes, true);
    if (!empty($notesArr['delivery'])) {
        echo '<div id="deliverynotes">';
        $cnt = 0;
        foreach ($notesArr['delivery'] as $dnote) {
            $cnt++;
            echo (($cnt>1)?'<br>':'').'<strong>Delivery Note:</strong> '.trim($dnote).'';
        }
        echo '</div>';
    }
}/**/
?>
        </div>
        
        <?php
            if (!empty($attach)) {
                foreach ($attach as $name) {
                    echo '<div style="page-break-before: always"></div>';
                    echo $this->partial('partial/project/docs/attach/'.$name.'.phtml'); 
                }
            }
        ?>
    </body>
</html>

