<table class="table table-bordered table-striped">
    <tbody>
    <tr>
        <th style="width: 200px">Projects Polled</th>
        <td><?php echo $data['count']['project']; ?></td>
    </tr>
    <tr>
        <th>Floors Polled</th>
        <td><?php echo $data['count']['drawing']; ?></td>
    </tr>
    <tr>
        <th>Devices Polled</th>
        <td><?php echo $data['count']['device']; ?></td>
    </tr>
    <tr>
        <th>Error Count</th>
        <td><?php echo $data['count']['error']; ?></td>
    </tr>
<!--    <tr>-->
<!--        <th>Warning Count</th>-->
<!--        <td>--><?php //echo $data['count']['warning']; ?><!--</td>-->
<!--    </tr>-->
    </tbody>
</table>

<div class="space20"></div>
<table class="table table-bordered table-striped" id="emergency_errors_tbl" >
    <thead>
    <tr>
        <th colspan="4" class="text-error"><i class="icon-warning-sign"></i> Error Breakdown</th>
    </tr>
    <tr>
        <th>Project</th>
        <th>Floor</th>
        <th>Serial</th>
        <th>Status</th>
        <th>Last Tested</th>
    </tr>
    </thead>
    <tbody>
<?php
    foreach ($data['projects'] as $projectName => $project) {
        if (empty($project['drawings'])) {
            continue;
        }

        foreach ($project['drawings'] as $drawingName => $drawing) {
            if (empty($drawing['errors'])) {
                continue;
            }

            foreach ($drawing['errors'] as $error) {
                echo '<tr><td>' . $projectName . '</td>' .
                    '<td>' . $drawingName . '</td>' .
                    '<td>' . $error[1] . '</td>' .
                    '<td>' . $error[2] . '</td>' .
                    '<td>' . $error[3] . '</td></tr>';
            }
        }
    }
?>
    </tbody>
</table>
