<p class="strong">
            <?php
                if(!empty($financing)) {
                    echo 'RE: Funded LED Solution<br />';
                }
            ?>
                Sabre Architectural Range
            </p>

            <p>
                Further to receiving your recent information please find below an illustration of the costs to provide linear remote phosphor for your project.
            </p>
            <p>
                The attached proposal has been generated based on information received either from yourselves or via a drawing submitted to us. 
                The proposal is to provide remote phosphor led linear lighting for the associated areas and for the lengths requested. 
                In order to achieve a linear run as close as possible to your required lengths we have broken the run into multiple smaller lengths, 
                the details of this breakdown is included in this document.
            </p>
            <p class="strong">Benfits of Sabre Architectural</p>
            <p style="margin-top:0" > 
                Combining the benefits of remote phosphor with a unique delivery system, Sabre architectural delivers uniform, glare free, colour consistent lighting 
                with the additional benefit of a clean and familiar off-state white appearance.
            </p>
            
            <h6 style="padding: 0; margin: 0">Product Features</h6>
            <ul >
                <li>Up to 30% higher system efficacy compared to white LED solutions</li>
                <li>Excellent lumen maintenance up to L70 100,000 hours</li>
                <li>High flux density (up to 4600 lumens per meter) and wide distribution</li>
                <li>High luminance values with low surface brightness leading to low glare Uniform consistent lighting</li>
                <li>Fully dimmable (DALI, 0-10V, DMX)</li>
                <li>Integrated heat sink, sleek and compact profile</li>
                <li>3 SDCM colour consistency</li>
                <li>CCT options 2700K, 3000K, 4000k and 500K with minimum 80 or 90 CRI</li>
                <li>Bespoke multiple length possibilities</li>
                <li>Available with a wide range of high performance, controllable power supplies 5 year warranty.</li>
            </ul>
            
            <h6  style="padding: 0; margin: 0">Our Guarantee</h6>
            <p style="margin-top:0"> 
                Our products come with a five year full product repair or replacement guarantee. If in the rare event one of our lights 
                fails during this time, we will repair or replace it at our cost. The standard lead time for product delivery is 4-8 weeks from date of order.
            </p>
            
            <p>
                I will contact you shortly in order to arrange a meeting to discuss this further but in the meantime, 
                should you have any questions, please do not hesitate to contact me.
            </p>            

            <p>To order please complete and sing the quotation acceptance form and return it to me and I will arrange for the order to be processed.</p>

            
            <p class="small">Please note that all costs are exclusive of delivery, installation, setup & commissioning of sensor & lighting controls, and VAT unless itemised on the attached Business Illustration.</p>

