<style>
    .table.config th {
        font-weight: bold;
        text-align: left;
        padding-right: 10px
    }
    
    .table.config td {
        font-weight: normal;
        text-align: left;
        padding-right: 50px
    }

    table.quote-space {
        width: 100%;
        border-spacing: 0;
        margin-bottom: 30px;
    }

    table.quote-space thead {
        border-bottom: 1px #ccc solid;
    }

    table.quote-space tbody tr td {
        border-bottom: 1px #ccc solid;
    }

    table.quote-space tfoot tr td {
        border-bottom: 1px #ccc solid;
        font-weight: bold;
    }

    table.quote-space tfoot tr th {
        border-bottom: 1px #ccc solid;
        text-align: left;
    }

</style>

<h3 >BOM - By Supplier</h3>
<?php
   if (!empty($billitems)) {
       $supplierData = array();
       foreach ($billitems as $item) {
           if (empty($supplierData[$item['supplierId']])) {
               $supplierData[$item['supplierId']] = array(
                   'name' => $item['supplierName'],
                   'items' => array(),
                   'total' => 0
               );
           }
           
           if ($item['typeId'] > 3 && $item['typeId'] !== 500) {
               continue;
           }
           
           $supplierData[$item['supplierId']]['items'][] = array(
                $item['model'],
                $item['quantity'],
                $item['ppu'],
                $item['priceMCD']
           );
           
           $supplierData[$item['supplierId']]['total'] += $item['priceMCD'];
       }
       
//       echo '<pre>', print_r($supplierData, true), '</pre>';
       foreach ($supplierData as $supplierId => $supplier) {
           if (empty($supplier['items'])) {
               continue;
           }
?>
<h4 class="underline"><?php echo $supplier['name']; ?></h4>
<table class="quote-space">
    <thead>
        <tr>
            <th class="left" >Product</th>
            <th class="right" style="width: 90px">Qty</th>
            <th class="right" style="width: 90px">CPU (&#163;)</th>
            <th class="right" style="width: 90px">Total (&#163;)</th>
        </tr>
    </thead>
    <tbody>
<?php
            foreach ($supplier['items'] as $item) {
?>
        <tr>
            <td><?php echo $item[0]; ?></td>
            <td class="right"><?php echo $item[1]; ?></td>
            <td class="right"><?php echo number_format($item[2], 2); ?></td>
            <td class="right"><?php echo number_format($item[3], 2); ?></td>
        </tr>
<?php
            }
?>        
    </tbody>
    <tfoot>
        <tr>
            <td>&nbsp;</td>
            <td class="right" colspan="3"><?php echo number_format($supplier['total'], 2); ?></td>
        </tr>
    </tfoot>
</table>

        <?php
       }
?>

<?php
   }
?>     