<?php
$this->inlineScript()
    ->appendFile('/js/forms/user/password.js')
        ;
?><div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-cog"></i> Change Your Password</h4>
            </div>
            <div class="widget-body relative">
                <div id="passwordLoader" class="loader"></div>
                <?php echo $this->form()->openTag($form); ?>
                <div class="control-group">
                    <label class="control-label">Current Password</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('password'));  ?>
                    </div>
                </div>
                <hr>
                <div class="control-group">
                    <label class="control-label">New Password</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('newPassword'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Confirm New Password</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('newPasswordConfirm'));  ?>
                    </div>
                </div>
                <hr />
                <button id="btn-savepassword" class="btn btn-primary" type="button"><i class="icon-shield"></i> Change Password</button>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>