<style>
    #tac_logo {
        width: 240px;
        position: absolute;
        right: 0;
        top: 0;
    }
    
    table.tac_content {
        border-spacing: 0px;
        border-collapse: separate;
        font-size: 6pt!important;
        line-height: 8pt!important;
        text-align: justify!important;
        width: 100%;
    }
    
    table.tac_content td {
        width: 50%;
        vertical-align: top;
    }
    
    table.tac_content td:first-child {
        padding-right: 8px;
    }
    
    table.tac_content td:last-child {
        padding-left: 8px;
    }
    
    table.tac_content ul {
        list-style: lower-roman;
        margin-top: 4px;
        padding-left: 16px;
    }
    
    table.tac_content li {
    }
    
</style>
<div style="position: relative; height: 100px">
    <h2>Terms & Conditions of Sale</h2>
    <img id="tac_logo" src="<?php echo $resourcesUri; ?>img/logo-8p3-1.png" />
</div>
<div>
    <table class="tac_content">
        <tr>
            <td>
                1. DEFINITIONS<br />
In these conditions:<br />
&quot;The Company&quot; means 8point3 Limited.<br />
&quot;The Buyer&quot; means the persons, firm or company entering into the contract with the Company.<br />
&quot;The Conditions&quot; means the conditions herein contained relating to the sale of the goods.<br />
&quot;The Contract&quot; means the contract between the Company and the Buyer, created upon acceptance of the Buyer’s order.<br />
&quot;The Goods&quot; means the goods supplied hereunder in accordance with the order. <br />
&quot;The Order&quot; means the order placed by the Buyer, based on the Company’s proposal.<br />
&quot;The Proposal&quot; means the proposal provided by the Company to the Buyer.<br />
&quot;The Warranty&quot; means the warranty agreement provided with a proposal.

<br /><br />2. GENERAL
<br />(a) Proposals for and acceptance of all orders are subject to these conditions and shall 
govern the contract to the exclusion of all other terms and conditions. The Buyer shall be 
deemed to have accepted these conditions on placing the order.<br />
(b) No addition to or variation from these terms and conditions shall have effect unless the 
same are expressly accepted by the Company in writing under the hand of a director of the 
Company.<br />
(c) The conditions represent the entire agreement and understanding of the parties and 
supersede any prior agreements, representations or undertakings.
<br /><br />3. PRICE
<br />(a) The price for goods will be as provided in the proposal, and confirmed to the Buyer in 
the Company’s invoice.<br />
(b) The Company reserves the right to vary from the price included in the proposal in the 
event the validity date of the proposal has expired. 
<br /><br />4. PAYMENT
<br />(a) A deposit may be payable as and when specified in the proposal. Any deposit is due on 
placement of an order. <br />
(b) Final payment shall be made within 15 days following the month of invoice unless
otherwise agreed and confirmed to the Buyer in the Company’s invoice.<br />
(c) In the event of late or part-payment, interest at the rate of 5% above the Company’s 
bank base lending rate shall be charged on the sum outstanding on a daily basis until full 
payment is received.<br />
(d) All prices quoted are exclusive of VAT, carriage, insurance, packing and all other duties, 
taxes or levies required to be paid under the contract.
<br /><br />5. DELIVERY
<br />(a) The appointment of carriers is at the Company’s sole discretion unless the Buyer 
indicates a specific carrier prior to proposal.<br />
(b) All reasonable efforts will be made by the Company to fulfil delivery dates as provided in 
the proposal. Time is not of the essence in the contract.
<br /><br />6. RISK AND PROPERTY
<br />(a) Risk in the goods passes on delivery.<br />
(b) Title in the goods will not pass to the Buyer until payment in full of the invoice.<br />
(c) Where the Buyer sells goods on to a third party title will pass immediately before the 
goods are delivered to such third party.<br />
(d) Where goods are attached to, or incorporated in other goods, or altered, title will not 
pass by virtue of such attachment or alteration, where the goods can be detached or 
removed.<br />
(e) The Buyer is required to store the goods supplied separately from any other goods in its 
possession until title has passed in accordance with sub-paragraphs (b) and (c) above.<br />
(f) If the Buyer is overdue in payment for the goods or other goods supplied by the 
Company, the Company may recover and sell the goods. The Company shall be entitled to 
take possession of the goods and is hereby granted licence to enter the Buyer’s premises 
for such purpose and may, if necessary, detach or remove the goods from other goods or 
equipment. This will not effect any other right the Company may have against the Buyer.<br />
(g) Until payment for the goods and all other goods which are supplied under these 
conditions:
<ul>
    <li>the Buyer shall hold the goods upon trust for the Company.</li>
    <li>if the goods are sold the Buyer shall hold the proceeds of sale on trust for the
        Company in a separate bank account specifically designated for this purpose.</li>
    <li>the Company reserves the right to trace the proceeds of sale received into any bank 
    or other account which the Buyer maintains.</li>
    <li>if the goods are sold the Company may by written demand require an assignment of 
        the Buyer’s right to recover the price from any third party</li>
                    <li>
if the Buyer incorporates the goods into, or uses the goods for manufacture of other 
goods, before payment in full of the price, the Company shall be entitled to take 
possession of the new goods and is hereby granted a licence to enter the Buyer’s 
premises for the purpose of recovering the new goods. The Company shall be entitled 
to sell the new goods (subject to any third party rights therein) and shall retain from the 
proceeds of sale the amount outstanding to the Company for the goods and pay any 
balance remaining to the Buyer.
                    </li>
</ul>
            </td>
            <td>
<br />7. WARRANTY AND LIABILITY
<br />(a) Subject to the conditions set out below, the Company warrants that the goods will be 
free from defects in material and workmanship for a period of up to 60 months from the
date of delivery and shall replace any goods which the Buyer proves to the satisfaction of
the Company to be faulty in accordance with this condition. The period of cover shall be 
defined in the Warranty provided in the proposal.
<br />(b) The warranty given in paragraph (a) is subject to the following conditions.
<ul>
    <li>the Company shall be under no liability in respect of any defect in the goods arising 
from any specification of the Buyer provided in its order or any tender.</li>
    <li>the Company shall be under no liability in respect of any defect arising from fair wear 
and tear, wilful damage, negligence, abnormal working conditions, failure to follow the 
Company’s instructions, misuse or alteration or repair of the goods without the 
Company’s written approval.</li>
    <li>the Company shall be under no liability under the above warranty if the total price for 
the goods has not been paid by the due date for payment.</li>
    <li>the above warranty does not extend to parts, materials or equipment not 
manufactured by the Company, in respect of which the Buyer shall only be entitled to 
the benefit of any warranty or guarantee provided by the manufacturer thereof to the 
Company.</li>
</ul>
(c) Subject as expressly provided in these conditions, all warranties, conditions or other 
terms implied by statute or common law are expressly excluded to the extent permitted by 
law.
<br />(d) Except in respect of death or personal injury caused by the Company’s negligence (or 
implied under the Consumer Safety Act 1987) the Company shall not be liable to the Buyer 
by reason of any representation, implied warranty, condition or other term or under the 
express terms of the contract for any consequential loss or damage (whether for loss of 
profit or otherwise), costs, expenses or other claims for consequential compensation 
whatsoever arising out of the supply of goods and the Company’s liability for direct loss
(otherwise than for death or personal injury) shall be limited to the value of the invoice for the 
contract.
<br /><br />8. STORAGE
The Company shall levy a storage charge to the Buyer for all goods stored by the Company 
within 1 month of the following;
<ul>
    <li>the Buyer failing to collect any goods from the Company’s premises following written 
        notification of availability for collection;</li>
    <li>the Buyer failing to take delivery of the goods or failing to make arrangements for 
        delivery upon written notification of readiness for dispatch.</li>
</ul>    
<br />9. RETURNS/CANCELLATION
<br />(a) The Company will not accept the return of any goods without its prior written consent. 
<br />(b) Where such consent is provided goods shall be returned at the Buyers expense.
<br />(c) Credit for goods returned will be provided by the Company at the goods resale value, 
less a handling fee of 25%, provided that the goods are returned in a condition suitable for 
resale.
<br /><br />10. ALTERATIONS/MODIFICATIONS
The Company may make such alterations or modifications as it deems necessary to the 
goods or their manufacture without notice to the Buyer from time to time.
<br /><br />11. NOTICES
All notices to be given under the contract shall be given by prepaid first class post or 
facsimile to the registered office or principal place of business of the party to be notified 
and shall be deemed to have been delivered if by letter at the expiration of 48 hours after 
posting and if by facsimile on receipt.
<br /><br />12. TERMINATION
Without prejudice to any other remedies the Company may have against the Buyer. The 
Company may terminate the contract on notice to the Buyer, upon the Buyer becoming 
bankrupt or insolvent or upon a resolution to wind up the Buyer being passed or a receiver, 
administrative receiver or administrator being appointed and shall be entitled to take 
possession of all goods supplied and unpaid for, in accordance with paragraph 6 hereof.
<br /><br />13. FORCE MAJEURE
The Company shall be entitled to cancel the contract or reduce the quantity of goods to be 
provided if it is prevented from providing the goods through any circumstances beyond its 
reasonable control including (but not limited to) industrial action, war, fire or prohibition or 
enactment of any kind, and will not be liable for any loss or damage incurred whatsoever 
arising therefrom.
<br /><br />14. GOVERNING LAW
The contract shall be governed by English law and subject to the exclusive jurisdiction of 
the High Court in England.
<br /><br /><strong>CONTROLLED	DOCUMENT
<br />8point3/Terms	and	Conditions/May 2012 V1.2AB</strong>
            </td>
        </tr>
    </table>
</div>