<?php
    $financing = ($figures['finance_amount'] > 0);
    $client = $project->getClient();

    
?><html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>RBS Lighting Upgrade - Branch Overview Sheet</title>
        
        <?php
            echo $this->partial('partial/project/docs/css.phtml'); 
        ?>
        
    </head>
    <body>
        <?php 
            if (!empty($footer['pages'])) {
                echo $this->partial('partial/project/docs/pages.phtml'); 
            }
            
        ?>
        <div>
            <?php 
                echo $this->partial('partial/project/docs/headers/sse.phtml'); 
                echo $this->partial('partial/project/docs/proposals/branchbom.phtml')
            ?>
        </div>
    </body>
</html>
