<?php
    $financing = ($figures['finance_amount'] > 0);
    $client = $project->getClient();

    
?><html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>8point3 LED document</title>
        
        <?php
            echo $this->partial('partial/project/docs/css.phtml'); 
        ?>
        
    </head>
    <body>
        <?php 
            if (!empty($footer['pages'])) {
                echo $this->partial('partial/project/docs/pages.phtml'); 
            }
            
        ?>
        <div>
            <?php 
                echo $this->partial('partial/project/docs/headers/letterhead.phtml'); 

                switch ($form['proposalstyle']) {
                    case 2: // architectural style
                        echo $this->partial('partial/project/docs/proposals/architectural.phtml'); 
                        break;
                    default:
                        echo $this->partial('partial/project/docs/proposals/standard.phtml'); 
                        break;
                }
            
            ?>
            


            <?php 
                echo $this->partial('partial/project/docs/signature.phtml'); 
            ?>
        </div>
        <?php
            if (!empty($attach)) {
                foreach ($attach as $name) {
                    echo '<div style="page-break-before: always"></div>';
                    echo $this->partial('partial/project/docs/attach/'.$name.'.phtml'); 
                }
            }
        ?>
    </body>
</html>
