<?php
$projectAddress = 'n\a';
foreach ($breakdown as $buildingId=>$building) {
        if (empty($buildingId) || empty($building['postcode'])) {
            continue;
        }
        $projectAddress = $building['address'] . ' ' . $building['postcode'];
    break;
}
?>
<style>
    #letterhead_logo {
        width: 240px;
        position: absolute;
        left: 0;
        top: 0;
    }
    
    #partnership_logo {
        width: 240px;
        position: absolute;
        right: 0;
        top: 0;
    }
    
    #letterhead_originator {
        position: absolute;
        right: 0;
        top: 0;
        font-size: 9pt;
        line-height: 10pt;
        text-align: right;
    }
    
    #letterhead_recipient {
        margin-top: 100px;
        margin-bottom: 30px;
    }
    
    #letterhead_date {
        position: absolute;
        right: 0;
    }
    
    .sub-heading {
        position: absolute;
        right: 0;
    }
</style>
<?php 
    echo '<img id="letterhead_logo" src="'.$resourcesUri.'img/sse/logo.png" />';
    if (!empty($this->title)) {
        echo  '<h5 class="sub-heading">' . $this->title . '</h5>';
    }
?>
<div id="letterhead_recipient">
    <br /><br />
    <strong>Project:</strong> <?php echo $project->getName(); ?> <br />
    <strong>Address:</strong> <?php echo $projectAddress; ?> <br />
    <strong>Reference:</strong> <?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT).'-'.str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT);
        if (isset ($invoiceNo)) {
            echo ' / '.$invoiceNo;
        }
    ?><br />
    <div id="letterhead_date">
        <?php echo date('jS F Y'); ?>
    </div>
</div>
