<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/dynamic-table/dashboard.js');


?>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-orange">
            <a data-original-title="" href="<?php echo $this->url('user',array('action'=>'profile')); ?>">
                <i class="icon-user"></i>
                <div class="info">Setup</div>
                <div class="status">My Profile</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-yellow">
            <a data-original-title="" href="/job/">
                <i class="icon-truck"></i>
                <div class="info"><?php echo $info['activeJobs']; ?></div>
                <div class="status">Jobs</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-grey">
            <a data-original-title="" href="/activity/">
                <i class="icon-comments-alt"></i>
                <div class="info"><?php echo $info['activityCount']; ?> Recent</div>
                <div class="status">Activity Log</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-blue double">
            <a data-original-title="" href="<?php echo $this->url('clients'); ?>">
                <i class="icon-eye-open"></i>
                <div class="info"><?php echo $info['activeClients']; ?> Owned</div>
                <div class="status">Clients</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-red">
            <a data-original-title="" href="/report/">
                <i class="icon-bar-chart"></i>
                <div class="info">Reports</div>
                <div class="status">Reporting and Statistics</div>
            </a>
        </div>
    </div>
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-blue">
            <a data-original-title="" href="#">
                <i class="icon-shopping-cart"></i>
                <div class="info">Assets</div>
                <div class="status">Tracking</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-green double">
            <a data-original-title="" href="/project">
                <i class="icon-tags"></i>
                <div class="info"><?php echo $info['activeProjects']; ?> Active</div>
                <div class="status">My Projects</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-orange">
            <a data-original-title="" href="/task/">
                <i class="icon-tasks"></i>
                <div class="info task-count"></div>
                <div class="status">Tasks</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-purple">
            <a data-original-title="" href="/contact/">
                <i class="icon-group"></i>
                <div class="info"><?php echo $info['companyContacts']/*, ' Project'.(($info['cancelledProjects']>1)?'s':'')/**/; ?></div>
                <div class="status">Company Contacts</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-grey ">
            <a data-original-title="" href="#">
                <i class="icon-external-link"></i>
                <div class="info">&#163;<?php echo number_format($info['monthlySales'], 0); ?></div>
                <div class="status">Total Monthly Sales</div>
            </a>
        </div>
    </div>
<?php if ($this->isGranted('project.surveyor')) { ?>        
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-blue ">
            <a data-original-title="" href="/project/survey">
                <i class="icon-list-alt"></i>
                <div class="info">Survey</div>
                <div class="status"></div>
            </a>
        </div>
    </div>
<?php } ?>        
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<div class="row-fluid">
    <div class="span7 responsive" data-tablet="span7 fix-margin" data-desktop="span7">
        <!-- BEGIN CALENDAR PORTLET-->
        <?php 
        $this->monthview = true;
        echo $this->partial('partial/panels/calendar.phtml'); ?>
        <!-- END CALENDAR PORTLET-->
    </div>
    <div class="span5">
        <!-- BEGIN PROGRESS PORTLET-->
        <div class="widget purple">
            <div class="widget-title">
                <h4><i class="icon-tasks"></i> Recent Active Projects</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                    <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body">
                <ul class="unstyled">
                <?php
                    if (!empty($projects)) {
                        foreach ($projects as $project) {
                    echo '<li>
                        <span class="btn linkable" href="/client-'.$project->getClient()->getClientId().'/project-'.$project->getProjectId().'"> <i class="icon-zoom-in"></i></span>  '.$project->getName().' - '.$project->getClient()->getClientId().'-'.$project->getProjectId().
                            ' <strong class="label '.(($project->getWeighting()<25)?'label-important':(($project->getWeighting()>65)?'label-success':'label-info')).'"> '.$project->getWeighting().'%</strong>
                        <div class="space10"></div>
                        <div class="progress '.(($project->getWeighting()<25)?'progress-danger':(($project->getWeighting()>65)?'progress-success':'')).'">
                            <div style="width: '.$project->getWeighting().'%;" class="bar"></div>
                        </div>
                    </li>';                            
                        }
                    }
                ?>
                </ul>
            </div>
        </div>
        <!-- END PROGRESS PORTLET-->
        <!-- BEGIN ALERTS PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-book"></i> Quick Contact Book</h4>
                <span class="tools">
                <a class="icon-chevron-down" href="javascript:;"></a>
                <a class="icon-remove" href="javascript:;"></a>
                </span>
            </div>
            <div class="widget-body" style="min-height: 230px">
                <table class="table table-striped table-hover" id="contacts_tbl">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Company</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END ALERTS PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span6">
        <!-- BEGIN NOTIFICATIONS PORTLET-->
        <?php echo $this->partial('partial/panels/remotephosphor.phtml'); ?>
         <!-- END NOTIFICATIONS PORTLET-->
    </div>
    <div class="span6 ">
        <!-- BEGIN CHAT PORTLET-->
        <?php echo $this->partial('partial/panels/activity.phtml'); ?>
        <!-- END CHAT PORTLET-->
    </div>
</div>
<?php echo $this->partial('partial/contact/dialog.phtml'); ?>
