<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
        ;

$projectMode = !empty($project);
if ($projectMode) {
    $url = "/activity/listclient/?clientId={$project->getClient()->getClientId()}&projectId={$project->getProjectId()}";
} else{
    $url = "/activity/listclient/?clientId={$client->getClientId()}";
}

$this->inlineScript()->captureStart();
echo <<<JS

    $(function(){
        var auditTbl = $('#activity_tbl').dataTable({
            sDom: "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
            sPaginationType: "bootstrap",
            oLanguage: {
                sLengthMenu: "_MENU_ records per page",
                oPaginate: {
                    sPrevious: "Prev",
                    sNext: "Next"
                }
            },
            bProcessing: true,
            bServerSide: true,
            iDisplayLength:25,
            aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
            aoColumns: [
                null,
                null,
                { "sClass": "hidden-phone" },
                { 'bSortable': true, },
                { "sClass": "hidden-phone" },
            ],
            sAjaxSource: "{$url}"
        });    

        jQuery('#activity_tbl_wrapper .dataTables_filter input').addClass("input-medium"); // modify table search input
        jQuery('#activity_tbl_wrapper .dataTables_length select').addClass("input-mini"); // modify table per page dropdown
            
        
        auditTbl.fnSort( [ [0,'desc'] ] );
        
    });

JS;
$this->inlineScript()->captureEnd();
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-table"></i> Detailed Activity Log</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
            </span>
            </div>
            <div class="widget-body">
<?php if (!empty($duration)) { ?>                
                <div class="alert alert-info">
                    <strong>Important Information:</strong> 
                    You have currently spent <?php 
                        if (empty($duration)) {
                           echo 'zero minutes'; 
                        } else {
                            $mins = ($duration % 60); 
                            $hours = floor(($duration/60) % 24);
                            $days = floor($duration/(60*60));

                            if (!empty($days)) {
                                echo $days.' day'.(($days==1)?'':'s'), ' '; 
                            }
                            if (!empty($hours)) {
                                echo $hours.' hour'.(($hours==1)?'':'s'), ' '; 
                            }
                            if (!empty($mins)) {
                                echo $mins.' minute'.(($mins==1)?'':'s'), ' '; 
                            }
                        }
                        
                        ?> on this <?php echo $projectMode?'project':'client'; ?>.
                </div>
<?php } ?>                
                <div class="clearfix">
                    <div class="btn-group pull-right">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#">Print</a></li>
                            <li><a href="#">Save as PDF</a></li>
                            <li><a href="#">Export to Excel</a></li>
                        </ul>
                    </div>
                </div>
                <div class="space15"></div>
                <table class="table table-striped table-bordered table-hover" id="activity_tbl">
                    <thead>
                    <tr>
                        <th style="width: 110px"><i class="icon-calendar"></i> Date</th>
                        <th style="width: 200px" ><i class="icon-question-sign"></i> Type</th>
                        <th style="width: 150px" class="hidden-phone"><i class="icon-user"></i> User</th>
                        <th ><i class="icon-info-sign"></i> Details</th>
                        <th style="width: 110px"><i class="icon-calendar"></i> Duration</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>