<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    //->appendFile('/js/dynamic-table/client.js')
        ;

if (!empty($project)) {
    $url = "/client-{$project->getClient()->getClientId()}/auditlist/?projectId={$project->getProjectId()}";
} else {
    $url = "/client-{$client->getClientId()}/auditlist/";
}


$this->inlineScript()->captureStart();
echo <<<JS

    $(function(){
        var auditTbl = $('#audit_tbl').dataTable({
            sDom: "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
            sPaginationType: "bootstrap",
            oLanguage: {
                sLengthMenu: "_MENU_ records per page",
                oPaginate: {
                    sPrevious: "Prev",
                    sNext: "Next"
                }
            },
            bProcessing: true,
            bServerSide: true,
            iDisplayLength:25,
            aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
            aoColumns: [
                null,
                null,
                { "sClass": "hidden-phone" },
                { 'bSortable': false, }
            ],
            sAjaxSource: "{$url}"
        });    

        jQuery('#audit_tbl_wrapper .dataTables_filter input').addClass("input-medium"); // modify table search input
        jQuery('#audit_tbl_wrapper .dataTables_length select').addClass("input-mini"); // modify table per page dropdown
            
        
        auditTbl.fnSort( [ [0,'desc'] ] );
        
    });

JS;
$this->inlineScript()->captureEnd();
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-table"></i> Detailed Audit Log</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
            </span>
            </div>
            <div class="widget-body">
                <div class="clearfix">
                    <div class="btn-group pull-right">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#">Print</a></li>
                            <li><a href="#">Save as PDF</a></li>
                            <li><a href="#">Export to Excel</a></li>
                        </ul>
                    </div>
                </div>
                <div class="space15"></div>
                <table class="table table-striped table-bordered table-hover" id="audit_tbl">
                    <thead>
                    <tr>
                        <th style="width: 110px"><i class="icon-calendar"></i> Date</th>
                        <th style="width: 200px" ><i class="icon-question-sign"></i> Type</th>
                        <th style="width: 150px" class="hidden-phone"><i class="icon-user"></i> User</th>
                        <th ><i class="icon-info-sign"></i> Details</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>