<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered tab" >
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Sub-Model</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
</div>
