<?php if (!empty($philips)) { ?>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-info">
            <strong>Important Notice:</strong> this product was exported from the Philips catalogue and any details that require changing should be verified by an administrator
        </div>
    </div>
</div>
<?php echo $this->partial('partial/product/philipsinfo.phtml'); ?>
<?php } ?>
<div class="row-fluid">
    <div class="blog span12">
        <div class="span2 <?php echo !$product->getActive()?'green':'red'; ?>">
            <a href="javascript:;" class="blog-features date active">
                <i class=" icon-<?php echo $product->getActive()?'ok':'ban-circle'; ?>"></i>
                <p class="month"><?php echo $product->getActive()?'Active':'Disabled'; ?></p>
            </a>
            <a href="/product-<?php echo $product->getProductId(); ?>/documents/" class="blog-features comments">
                <i class=" icon-gear"></i>
                <p class="info">0 Documents</p>
            </a>
            <a href="/product-<?php echo $product->getProductId(); ?>/images/" class="blog-features comments">
                <i class=" icon-picture"></i>
                <p class="info">0 Images</p>
            </a>
            <a href="javascript:;" class="blog-features comments">
                <i class=" icon-info"></i>
                <p class="info">Product #<?php echo str_pad($product->getProductId(), 5, "0", STR_PAD_LEFT); ?></p>
            </a>
        </div>
        <div class="span10">
            <h2>
                <?php echo $product->getModel(); ?>
            </h2>
            <p>
                BRAND <a href="javascript:;" class="author"><?php echo strtoupper($product->getBrand()->getName()); ?></a> |  CREATED: <?php echo $product->getcreated()->format('d/m/Y H:i'); ?>
            </p>
            <h5>Product Configuration Details</h5>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th colspan="2">
                            Product Information<a href="/product-<?php echo $product->getProductId();?>/setup/" class="" style="float: right; font-weight: normal">Modify Product Settings&nbsp;&nbsp;<i class=" icon-cog"></i></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 120px">
                            Product Model
                        </td>
                        <td>
                            <?php echo $product->getModel(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Product Brand
                        </td>
                        <td>
                            <?php echo $product->getBrand()->getName(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Product Supplier
                        </td>
                        <td>
                            <?php echo $product->getSupplier()->getName(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Product Type
                        </td>
                        <td>
                            <?php echo $product->getType()->getName(); ?>
                        </td>
                    </tr>
                    <!--<tr>
                        <td >
                            Product Build
                        </td>
                        <td>
                            <?php echo $product->getBuild()->getName(); ?>
                        </td>
                    </tr><!-- -->
                    <tr>
                        <td >
                            Product Description
                        </td>
                        <td>
                            <?php echo $product->getDescription(); ?>
                        </td>
                    </tr>
                    
                    <tr>
                        <td >
                            CPU / PPU
                        </td>
                        <td>&#163;<?php echo number_format($product->getCPU(),2); ?>&nbsp;&nbsp;/&nbsp;&nbsp;&#163;<?php echo number_format($product->getPPU(),2); ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Sage Code
                        </td>
                        <td><?php echo $product->getProductId(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Power
                        </td>
                        <td><?php echo round($product->getPwr(), 2); ?>w
                        </td>
                    </tr>
<?php if (!empty($philips)) { ?>
                    <tr>
                        <td >Philips Information</td>
                        <td><a href="#modalProductInfo" role="button" class="label label-success" data-toggle="modal"><?php echo $philips->getModel(); ?></a>
                        </td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-cogs"></i> Bill Of Materials</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <table class="table table-striped table-bordered table-advance table-hover" id="products_tbl">
                    <thead>
                        <tr>
                            <th ><i class="icon-cog"></i> Component Name</th>
                            <th class="hidden-phone"> Stock Code</th>
                            <th style="width: 110px"> Quantity</th>
                            <th style="width: 140px"> Price (inc MCD)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">
                                No items found
                            </td>
                        </tr>
                        <tr>
                            <td colspan="4">&nbsp;</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="2">TOTAL</th>
                            <td class="row-right">0</td>
                            <th class="row-right">&#163;<?php echo number_format(0,2); ?></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>