<?php
$this->inlineScript()
    ->appendFile('/js/forms/tools/iot.js');;


?>
<div class="relative">
    <div id="pageLoader" class="loader"></div>
    <div class="row-fluid">
        <div class="metro-nav metro-fix-view">
            <div class="metro-nav-block  nav-block-grey double" id="btn-synchronize">
                <a href="javascript:">
                    <div class="text-center">
                        <i class="icon-refresh"></i>
                    </div>
                    <div class="status">Synchronize Branches</div>
                </a>
            </div>
        </div>
    </div>
</div>
