<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/dynamic-table/building.js');



?><div class="row-fluid">
    <div class="span12">
    <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget red">
            <div class="widget-title">
                <h4><i class="icon-2x"></i>Buildings</h4>
                    <span class="tools">
                        <a href="javascript:;" class="icon-chevron-down"></a>
                    </span>
            </div>
            <div class="widget-body">
                <div>
                    <div class="clearfix">
<?php if ($this->isGranted('client.write')) { ?>                    
                        <div class="btn-group pull-left">
                            <button class="btn green linkable" href="/client-<?php echo $client->getclientId(); ?>/building/add/">
                                Add New <i class="icon-plus"></i>
                            </button>
                        </div>
<?php } ?>                    
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space15"></div>
                    <table class="table table-striped table-bordered table-hover" id="buildings_tbl">
                        <thead>
                        <tr>
                            <th style="width: 180px">Name</th>
                            <th style="width: 90px">Postcode</th>
                            <th style="width: 250px">Address</th>
                            <th >Notes</th>
                            <th style="width: 40px">&nbsp;</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php
                                if (!empty($buildings)) {
                                    $markers = '';
                                    $locations = array();
                                    $keys = array();
                                    $i = 0;
                                    foreach ($buildings as $building) {
                                        $i++;
                                        echo '<tr>
                                                <td>'.ucwords($building->getName()).'</td>
                                                <td>'.strtoupper($building->getAddress()->getPostcode()).'</td>
                                                <td>'.ucwords($building->getAddress()->assemble(', ', array('postcode'))).'</td>
                                                <td>'.$building->getNotes().'</td>
                                                <td><a href="/client-'.$client->getClientId().'/building-'.$building->getBuildingId().'/" class="btn btn-primary action-edit"><i class="icon-pencil"></i></a></td>
                                            </tr>';
                                        $key = $building->getAddress()->getLat().'-'.$building->getAddress()->getLng();
                                        if (!empty($keys[$key])) {
                                            $keys[$key]++;
                                            $locations[$key] = preg_replace('/([<]strong[\/>])([^<]*)([<][\/]strong[>])/', '$1$2<br>'.$keys[$key].'. '.ucwords($building->getName()).'$3', $locations[$key]);
                                        } else {
                                            $keys[$key]=1;
                                            $locations[$key] = "'<p><strong>".$keys[$key].'. '.ucwords($building->getName())."</strong><br />{$building->getAddress()->assemble('<br />')}</p>',".
                                                $building->getAddress()->getLat().','.
                                                $building->getAddress()->getLng().','.
                                                $i;
                                        }
                                    }
                                }
                                
                                $location = empty($locations)?'':'var locations = [['.implode('],[',$locations).']];';
                            ?>
<?php 
$this->inlineScript()->appendFile('http://maps.googleapis.com/maps/api/js?v=3.7&key=AIzaSyA4Spe8FXyD4dgvEf0fwBI26mnfrO21T4o&sensor=false&region=GB');

$this->inlineScript()->captureStart();
echo <<<JS
//google map
    var map = null;
    var geocoder = null;
	var infowindow = new google.maps.InfoWindow();

    {$location}

    function initialize() {
        var myLatlng = new google.maps.LatLng(51.507351, -0.127758);
        var mapOptions = {
            zoom: 10,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        var marker, i;
        var bounds = new google.maps.LatLngBounds();

        
        for (i = 0; i < locations.length; i++) {  
              marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                map: map
              });

              google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function() {
                  infowindow.setContent(locations[i][0]);
                  infowindow.open(map, marker);
                }
              })(marker, i));

            bounds.extend(marker.position);
        }
    
        map.fitBounds(bounds);
    }

    
    google.maps.event.addDomListener(window, 'load', initialize);

JS;
$this->inlineScript()->captureEnd();
?>                            
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
    <!-- END EXAMPLE TABLE widget-->
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BLANK PAGE PORTLET-->
        <div class="widget">
            <div class="widget-title">
                <h4><i class="icon-map-marker"></i> Location Details </h4>
              <span class="tools">
                  <a href="javascript:;" class="icon-chevron-down"></a>
              </span>
            </div>
            <div class="widget-body">
                <div class="contact-us">
                    <div class="row-fluid">
                        <div id="map-canvas" style="width: 100%; height: 400px"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END BLANK PAGE PORTLET-->
    </div>
</div>