<style>
    * {
        font-family: Verdana, Geneva, sans-serif;
        font-size: 10pt;
        line-height: 15pt;
    }

    body {
        margin: 0px 20px;
    }

    .break-after {
      page-break-after: always;
    }

    .break-before {
      page-break-before: always;
    }

    #header{
      position: fixed;
    }

    #header {
      top: 0;
    }

    .strong {
        font-weight: bold;
    }

    h1 {
        font-size: 16pt!important;
    }

    h2 {
        font-size: 14pt!important;
    }

    h3 {
        font-size: 13pt!important;
    }

    h4 {
        font-size: 12pt!important;
    }

    h5 {
        font-size: 11pt!important;
    }
    
    h6 {
        font-size: 10pt!important;
    }
    
    .clear {
        clear: both;
    }
    
    table .left {
        text-align: left;
    }

    table .right {
        text-align: right;
    }

    table .center {
        text-align: center;
    }
    
    .red {
        color: #d00;
    }
    
    .green {
        color: #090;
    }

    .blue {
        color: #369;
    }
    
    .underline {
        text-decoration: underline;
    }
    
    .upper {
        text-transform: uppercase;
    }
    
    .no-margin {
        margin: 0!important;
    }

    .no-margin-bot {
        margin-bottom: 0!important;
    }

    .no-margin-top {
        margin-top: 0!important;
    }

    .no-margin-left {
        margin-left: 0!important;
    }

    .no-margin-right {
        margin-right: 0!important;
    }

</style>