<p>
	<br />Yours sincerely<br><br>
	<?php 
	if(!empty($user->getSignature())){
		echo '<img src="'.$resourcesUri.'user/signature/'.$user->getSignature().'.png" alt="" />';
	} else {
		echo '<br><br>';
	} 
	
	?>
	<br><br>
	<?php echo $user->getName(); ?><br>
	<?php if (false){//$user->getCompany()->getPartner() == 1) { 	
		echo 'On behalf of <span style="font-weight: bold">'.$user->getCompany()->getName(),'</span><br />';
	} else {
		echo ucwords($user->getPosition()->getLabel()).'<br />';
		echo '<a href="mailto: ',$user->getEmail(),'">', $user->getEmail(), '</a>';
	}
	
	?>
</p>