<?php
/*$this->headLink()
    ->appendStylesheet('/assets/dropzone/css/basic.css')
    ->appendStylesheet('/assets/dropzone/css/dropzone.css')
    ;
/**/
$this->inlineScript()
    ->appendFile('/js/forms/project/viewer.js')
;/**/


?><div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-folder-open"></i> File Manager</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <div class="row-fluid">
                    <div class="btn-toolbar" id="fileOptions">
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-primary dropdown-toggle"><i class="icon-bolt"></i> Documents <span class="caret"></span></button>
                            <ul class="dropdown-menu"><?php
                                if (!empty($documentCategories)) {
                                    $loc = '';
                                    foreach ($documentCategories as $category) {
                                        if (!empty($loc) && ($loc != $category['location'])) {
                                            echo '<li class="divider"></li>';
                                        } elseif(empty($loc)) {
                                            $loc = $category['location'];
                                        }
                                        
                                        echo '<li><a href="#" data-category="'.$category['documentCategoryId'].'">'.$category['name'].'</a></li>';
                                    }
                                }
                            
                            ?>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-danger dropdown-toggle"><i class="icon-camera-retro"></i> Photos <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <?php
                                if (!empty($imageCategories)) {
                                    foreach ($imageCategories as $category) {
                                        echo '<li><a href="#" data-category="'.$category['documentCategoryId'].'">'.$category['name'].'</a></li>';
                                    }
                                }
                            
                            ?>
                                <li class="divider"></li>
                                <li><a href="#" data-category="13">All Photos</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-warning dropdown-toggle"><i class="icon-bar-chart"></i> Accounts <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <?php
                                if (!empty($accountCategories)) {
                                    foreach ($accountCategories as $category) {
                                        echo '<li><a href="#" data-category="'.$category['documentCategoryId'].'">'.$category['name'].'</a></li>';
                                    }
                                }
                            
                            ?>
                            </ul>
                        </div>
                        
                        <!--<div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-success dropdown-toggle"><i class="icon-building"></i> Survey <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Under Construction</a></li>
                            </ul>
                        </div><!-- -->
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-success dropdown-toggle"><i class="icon-wrench"></i> Install <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">No Categories Available</a></li>
                            </ul>
                        </div>
                        <!--<div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-inverse dropdown-toggle"><i class="icon-folder-close-alt"></i> Other <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Under Construction</a></li>
                            </ul>
                        </div><!-- -->
                    </div>
                </div>
                <hr>
                <div style="min-height: 400px" class="relative">
                    <div id="fileViewLoader" class="loader"></div>
                    <h3 id="fileViewName">Please Select A Category From Above</h3>
                    <table class="table table-striped table-row-middle" id="tblDocumentViewer">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Size</th>
                                <th>Type</th>
                                <th>Originator</th>
                                <th>Created</th>
                                <th style="width: 50px">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="6">No documents found</td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>    
                <form id="documentViewFrm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/list"></form>
                <div class="alert alert-block alert-warning no-margin-bot">
                    <h4 class="alert-heading">Important Information:</h4>
                    <p>
                        You can view all files uploaded to this <?php echo ($project->getStatus()->getJob())?'job':(($project->getType()==3)?'trial':'project'); ?> (via PROJIS or Google Drive) and upload additional files in the <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/<?php echo ($project->getStatus()->getJob())?'job':(($project->getType()==3)?'trial':'project'); ?>-<?php echo $project->getProjectId(); ?>/document/explorer/">project explorer</a> system.
                    </p>
                </div>
            </div>
        </div>
    </div>
    
</div>
<form id="documentDownloadFrm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/download" target="download-frame">
    <input type="hidden" name="documentListId" value="" />
</form>
<iframe id="download-frame" name="download-frame" style="width:1px; height: 1px; visibility: hidden"></iframe>