<?php echo $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>Login</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/css/style.css" rel="stylesheet" />
    <link href="/css/style-responsive.css" rel="stylesheet" />
    <link href="/css/style-default.css" rel="stylesheet" id="style_color" />
    <script src="/js/jquery-1.8.3.min.js"></script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="lock">
    <?php if (empty($boxmode)) { ?>
    <div class="lock-header">
        <!-- BEGIN LOGO -->
        <h1>PROJIS<sub>8p3</sub></h1>
        <a class="center" id="logo" href="index.html">
            more information
        </a>
        <!-- END LOGO -->
    </div>
    <?php } ?>
    <div class="login-wrap">
        <?php echo $this->content; ?>
    </div>
    <!-- BEGIN JAVASCRIPTS -->
    <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>