<div class="row-fluid relative">
    <div class="span2">
        <div class="metro-nav metro-fix-view">
            <div class="metro-nav-block nav-block-green">
                <a href="<?php echo $this->url('assets',array('action'=>'installers')); ?>" class="text-center" data-original-title="">
                    <span class="value">
                        <i class="icon-barcode"></i>
                    </span>
                    <div class="status">Installers' Sheet</div>
                </a>
            </div>
        </div>
    </div>
    <div class="span10">
        <div id="profileLoader" class="loader"></div>
        <table class="table">
            <thead>
                <tr>
                    <th >Details</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>The Installers' barcode sheet system allows for the uploading of 
                        project barcode sheets (post installation).</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>