<?php

if (empty($drawings)) { ?>
    <div class="row-fluid">
        <div class="span12">
            <p>This branch does not have any uploaded drawings.</p>
        </div>
    </div>
    <?php
    return;
}

$this->headLink()
    ->appendStylesheet('/assets/speech/speech-bubbles.css');



$this->inlineScript()
    ->appendFile('/assets/moment/moment.js')
    ->appendFile('/assets/konvajs/konva.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/forms/liteip/locator.js')
    ->appendFile('/js/forms/liteip/locator.image.js');
;



$this->inlineScript()->captureStart();
echo <<<JS
<!-- 3 -->
$(function() {
    $("#fDrawingId").trigger('change');
});
JS;
$this->inlineScript()->captureEnd();
?>
<div class="row-fluid">
    <div class="metro-nav metro-fix-view">
        <div class="metro-nav-block  nav-block-blue" id="btn-prev-drawing">
            <a href="javascript:">
                <div class="text-center">
                    <i class="icon-double-angle-left"></i>
                </div>
                <div class="status">Previous Drawing</div>
            </a>
        </div>
        <div class="metro-nav-block  nav-block-blue" id="btn-next-drawing">
            <a href="javascript:">
                <div class="text-center">
                    <i class="icon-double-angle-right"></i>
                </div>
                <div class="status">Next Drawing</div>
            </a>
        </div>
        <div class="metro-nav-block  nav-block-grey" id="btn-reload">
            <a href="javascript:">
                <div class="text-center">
                    <i class="icon-refresh"></i>
                </div>
                <div class="status">Reload</div>
            </a>
        </div>
    </div>
    <div style="visibility: hidden;">
        <label><select size="1" id="fDrawingId" data-request-url="/branch-<?php echo $project->getProjectId(); ?>/%a/"><?php
                if (!empty($drawings)) {
                    foreach ($drawings as $drawing) {
                        echo '<option value="' . $drawing->getDrawingID() . '" data-width="' . $drawing->getWidth() . '" data-height="' . $drawing->getHeight() . '">' . $drawing->getDrawing(true) . '</option>';
                    }
                }
                ?></select></label>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <p>
            Displayed below are the branch floor-plans and associated device list.
            To change the selected floor-plan click on the next or previous buttons.
            <br>Hover over a plotted device to view its status details.
            Use the device type drop-down to filter devices by type or serial number.

        </p>
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-pencil"></i> Floor-Plan <span id="drawingTitle"></span></h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="drawingLoader" class="loader"></div>
                <div class="row-fluid">
                    <div class="span2">
                        <select class="span12" id="sel-device-view-mode">
                            <option value="1">Show all devices</option>
                            <option value="2">Show emergency devices</option>
                            <option value="3">Show non-emergency devices</option>
                            <option value="4">Show failing devices</option>
                            <option value="5">Show selected devices</option>
                        </select>
                    </div>
                    <div class="span8">
                        <div class="controls ">
                            <div class="input-append span12">
                                <input id="inp-show-serials" type="text" class=" small span10" value=""  placeholder="Enter the serial list separated by spaces or commas">
                                <button type="button" class="btn" id="btn-show-serials">
                                    Go
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="space10"></div>

                <div id="locator-wrapper" class="relative">
                    <div class="bubble right" id="device-popover">
                        <label>Id: <span class="device-id">-</span></label>
                        <label>Serial: <span class="device-serial">-</span></label>
                        <label>Emergency: <span class="device-emergency">-</span></label>
                        <label>Status: <span class="device-status">-</span></label>
                        <label>Checked: <span class="device-checked">-</span></label>
                    </div>
                    <div id="locator-container"></div>
                </div>
                <div class="space10"></div>
                <hr>
                <div class="row-fluid">
                    <div class="span2">
                        <label>Id: <span class="device-id">-</span></label>
                    </div>
                    <div class="span2">
                        <label>Serial: <span class="device-serial">-</span></label>
                    </div>
                    <div class="span2">
                        <label>Emergency: <span class="device-emergency">-</span></label>
                    </div>
                    <div class="span3">
                        <label>Status: <span class="device-status">-</span></label>
                    </div>
                    <div class="span2">
                        <label>Checked: <span class="device-checked">-</span></label>
                    </div>
                </div>
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-mobile-phone"></i> Devices</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="locatorLoader" class="loader"></div>
                <table class="table table-bordered table-striped" id="devices_tbl">
                    <thead>
                    <tr>
                        <th>Serial</th>
                        <th >Emergency</th>
                        <th >Status</th>
                        <th >Floor</th>
                        <th >Project</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>