<?php
$this->inlineScript()
    ->appendFile('/js/forms/liteip/emergency.js?' . time());
;
?>
<div class="relative">
    <div id="emergencyLoader" class="loader"></div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget green">
                <div class="widget-title">
                    <h4><i class="icon-warning-sign"></i> Emergency Report</h4>
                    <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                    <a href="javascript:;" class="icon-remove"></a>
                    </span>
                </div>
                <div class="widget-body relative">
                    <div class="space10"></div>
                    <div class="navbar navbar-static" id="navbar-example">
                        <div class="navbar-inner">
                            <div style="width: auto;" class="container">
                                <a href="#" class="brand">Options</a>
                                <ul role="navigation" class="nav">
                                    <li class="dropdown">
                                        <a data-toggle="dropdown" class="dropdown-toggle" role="button" id="drop2" href="#">Downloads <b class="caret"></b></a>
                                        <ul aria-labelledby="drop2" role="menu" class="dropdown-menu">
                                            <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/exportemergencyreport/?warnings=<?php echo ($this->isGranted('branch.warnings.read') ? '1' : '0'); ?>" tabindex="-1" role="menuitem">Emergency Report CSV</a></li>
                                            <li role="presentation"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/document/exportemergencyreport/?pdf=1&warnings=<?php echo ($this->isGranted('branch.warnings.read') ? '1' : '0'); ?>" class="btn-config-export-csv">Emergency Report PDF</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <table class="table table-bordered table-striped" id="emergency_summary_tbl" data-request-url="/branch-<?php echo $project->getProjectId(); ?>/%a/">
                        <tbody>
                        <tr>
                            <th style="width: 200px">Error count</th>
                            <td id="errorCount">0</td>
                        </tr>
                        <tr>
                            <th >No Fault</th>
                            <td id="noFaultCount">0</td>
                        </tr>
                        <tr>
                            <th>Total devices polled</th>
                            <td id="devicesCount">0</td>
                        </tr>
                        </tbody>
                    </table>

                    <div class="space20"></div>
                    <div class="row-fluid" id="emergency_errors_section" style="display: none">
                        <div class="span12">
                            <table class="table table-bordered table-striped" id="emergency_errors_tbl" >
                                <thead>
                                <tr>
                                    <th colspan="4" class="text-error"><i class="icon-warning-sign"></i> Error Breakdown</th>
                                </tr>
                                <tr>
                                    <th>Serial</th>
                                    <th >Status</th>
                                    <th >Floor</th>
                                    <th >Last Tested</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <?php if ($this->isGranted('branch.warnings.read')) { ?>
                        <div class="space20"></div>
                        <div class="row-fluid" id="emergency_warnings_section" style="display: none">
                            <div class="span12">
                                <table class="table table-bordered table-striped" id="emergency_warnings_tbl" >
                                    <thead>
                                    <tr>
                                        <th colspan="4" class="text-error"><i class="icon-warning-sign"></i> Warning Breakdown</th>
                                    </tr>
                                    <tr>
                                        <th>Serial</th>
                                        <th >Status</th>
                                        <th >Floor</th>
                                        <th >Last Tested</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>

</div>