<?php
$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/forms/branch/dashboard.js');


?>
<div class="row-fluid">
    <div class="blog span12">
        <div class="span10">
            <h2>
                <?php echo $project->getName(); ?>
            </h2>
            <p>
                OWNER <a href="javascript:;" class="author"><?php echo strtoupper($project->getClient()->getUser()->getHandle()); ?></a> |
                CREATED: <?php echo $project->getcreated()->format('d/m/Y H:i'); ?> |
                REFERENCE: <?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT),'-',str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT) ?> |
                PROVIDER: <?php echo $project->getLipProject()->getProjectID(); ?>
            </p>
            <h5>Weighting<span class="pull-right"><?php echo $weighting; ?>%</span></h5>
            <div id="slider-range-min" class="slider"></div>
            <div class="progress progress-striped progress-<?php
            if ($weighting < 20) {
                echo 'danger';
            } elseif ($weighting < 40) {
                echo 'danger';
            } elseif ($weighting < 60) {
                echo 'warning';
            } elseif ($weighting < 80) {
                echo 'striped';
            } else {
                echo 'success';
            }

            ?>">
                <div style="width: <?php echo $weighting; ?>%;" class="bar"></div>
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th colspan="2">
                        Project Information
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td style="width: 120px">
                        Project Status
                    </td>
                    <td>
                        <?php
                        $labelTypes = array(
                            'important',
                            'info',
                            'success',
                            'warning',
                            'default',
                        );
                        $labelIdx = 0;
                        $validStates = array(20, 21, 22, 23, 101);
                        foreach ($project->getStates() as $state) {
                            if (!in_array($state->getStateId(), $validStates)) {
                                continue;
                            }

                            echo '<span class="label label-'.$labelTypes[$labelIdx].' label-mini">'.ucwords($state->getName()).'</span>&nbsp;';
                            $labelIdx++;
                            if ($labelIdx>(count($labelTypes)-1)) {
                                $labelIdx = 0;
                            }
                        }
                        if ($labelIdx === 0) {
                            echo 'unavailable';
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td >
                        Devices
                    </td>
                    <td><?php
                        echo $deviceCount ? $deviceCount : 0;
                        ?>
                    </td>
                </tr>
                <tr>
                    <td >
                        Branch Address
                    </td>
                    <td><?php
                        echo $project->getAddress() ? $project->getAddress()->assemble() : $project->getLipProject()->getPostCode(true);
                        ?>
                    </td>
                </tr>
                <tr>
                    <td >
                        Notes
                    </td>
                    <td>
                        No notes added to project
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="span2 <?php echo $commissioned ? 'green' : ($installed ? 'orange' : 'red'); ?>">
            <a href="javascript:;" class="blog-features date active">
                <i class=" icon-<?php echo $commissioned ? 'check' : ($installed ? 'flag' : 'time'); ?>"></i>
                <p class="month"><?php echo $commissioned ? 'Commissioned' : ($installed ? 'Installed' : 'Pending'); ?></p>
            </a>
            <a href="/branch-<?php echo $project->getProjectId(); ?>/devicelayout/" class="blog-features comments">
                <i class="icon-sitemap"></i>
                <p class="info">Device Layout</p>
            </a>
            <a href="/branch-<?php echo $project->getProjectId(); ?>/emergencyreport/" class="blog-features comments">
                <i class=" icon-file-text"></i>
                <p class="info">Emergency Report</p>
            </a>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-mobile-phone"></i> Devices</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="locatorLoader" class="loader"></div>
                <table class="table table-bordered table-striped" id="devices_tbl" data-request-url="/branch-<?php echo $project->getProjectId(); ?>/%a/">
                    <thead>
                    <tr>
                        <th>Serial</th>
                        <th >Emergency</th>
                        <th >Status</th>
                        <th >Floor</th>
                        <th >Project</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>