<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/forms/dashboard/customer.js');


?>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-orange">
            <a data-original-title="" href="<?php echo $this->url('user',array('action'=>'profile')); ?>">
                <i class="icon-user"></i>
                <div class="info">Setup</div>
                <div class="status">My Profile</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-blue">
            <a data-original-title="" href="/map/">
                <i class="icon-globe"></i>
                <div class="info"><?php echo $info['activeProjects']; ?> Branches</div>
                <div class="status">Map View</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-red">
            <a data-original-title="" href="/report/">
                <i class="icon-bar-chart"></i>
                <div class="info">Reports</div>
                <div class="status">Reporting and Statistics</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-green">
            <a data-original-title="" href="/project">
                <i class="icon-check"></i>
                <div class="info"><?php echo $info['activeProjects']; ?></div>
                <div class="status">Commissioned Branches</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-grey">
            <a data-original-title="" href="/project">
                <i class="icon-calendar"></i>
                <div class="info"><?php echo $info['activeProjects']; ?></div>
                <div class="status">Pending Branches</div>
            </a>
        </div>
    </div>
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN PROGRESS PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-tasks"></i> Branches</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                    <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body">
                <table class="table table-bordered table-advance table-responsive" id="branches_tbl">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Postcode</th>
                            <th>Address</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <!-- END PROGRESS PORTLET-->
    </div>
</div>

